-- 308_agency_storage_and_tbh_reports: the two storage.objects policy statements
-- exec_sql cannot run (storage.objects is owned by supabase_storage_admin).
-- Paste into the SQL editor of any project that had 308 applied through
-- scripts/run-migration.ts --skip-storage. Idempotent.


-- Lock all direct authenticated access to the bucket. Reads happen via
-- short-lived signed URLs generated by /api/intel/agencies/[id]/
-- documents/[documentId]/download after the API validates the user
-- can see the parent agency_documents row.

DROP POLICY IF EXISTS "agency_documents_storage_service_all"
  ON storage.objects;

CREATE POLICY "agency_documents_storage_service_all"
  ON storage.objects
  FOR ALL
  TO service_role
  USING (bucket_id = 'agency-documents')
  WITH CHECK (bucket_id = 'agency-documents');

