-- ============================================
-- DISABLE RLS FOR DEMO MODE
-- ============================================
-- Run this in Supabase SQL Editor to allow all queries
-- without auth. For demo/development only.
--
-- The RLS policies in 006 have a circular reference on
-- user_profiles (super_admin check queries user_profiles
-- which triggers its own RLS check → infinite recursion).
--
-- For production, fix the policies to use auth.jwt()
-- claims instead of subqueries on user_profiles.
-- ============================================

ALTER TABLE organisations DISABLE ROW LEVEL SECURITY;
ALTER TABLE venues DISABLE ROW LEVEL SECURITY;
ALTER TABLE venue_config DISABLE ROW LEVEL SECURITY;
ALTER TABLE venue_ai_config DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE weddings DISABLE ROW LEVEL SECURITY;
ALTER TABLE people DISABLE ROW LEVEL SECURITY;
ALTER TABLE contacts DISABLE ROW LEVEL SECURITY;
ALTER TABLE booked_dates DISABLE ROW LEVEL SECURITY;
ALTER TABLE interactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE drafts DISABLE ROW LEVEL SECURITY;
ALTER TABLE draft_feedback DISABLE ROW LEVEL SECURITY;
ALTER TABLE engagement_events DISABLE ROW LEVEL SECURITY;
ALTER TABLE lead_score_history DISABLE ROW LEVEL SECURITY;
ALTER TABLE heat_score_config DISABLE ROW LEVEL SECURITY;
ALTER TABLE auto_send_rules DISABLE ROW LEVEL SECURITY;
ALTER TABLE phrase_usage DISABLE ROW LEVEL SECURITY;
ALTER TABLE email_sync_state DISABLE ROW LEVEL SECURITY;
ALTER TABLE search_trends DISABLE ROW LEVEL SECURITY;
ALTER TABLE weather_data DISABLE ROW LEVEL SECURITY;
ALTER TABLE economic_indicators DISABLE ROW LEVEL SECURITY;
ALTER TABLE anomaly_alerts DISABLE ROW LEVEL SECURITY;
ALTER TABLE ai_briefings DISABLE ROW LEVEL SECURITY;
ALTER TABLE natural_language_queries DISABLE ROW LEVEL SECURITY;
ALTER TABLE review_language DISABLE ROW LEVEL SECURITY;
ALTER TABLE guest_list DISABLE ROW LEVEL SECURITY;
ALTER TABLE timeline DISABLE ROW LEVEL SECURITY;
ALTER TABLE budget DISABLE ROW LEVEL SECURITY;
ALTER TABLE seating_tables DISABLE ROW LEVEL SECURITY;
ALTER TABLE seating_assignments DISABLE ROW LEVEL SECURITY;
ALTER TABLE sage_conversations DISABLE ROW LEVEL SECURITY;
ALTER TABLE sage_uncertain_queue DISABLE ROW LEVEL SECURITY;
ALTER TABLE planning_notes DISABLE ROW LEVEL SECURITY;
ALTER TABLE contracts DISABLE ROW LEVEL SECURITY;
ALTER TABLE checklist_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE vendor_recommendations DISABLE ROW LEVEL SECURITY;
ALTER TABLE inspo_gallery DISABLE ROW LEVEL SECURITY;
ALTER TABLE knowledge_base DISABLE ROW LEVEL SECURITY;
ALTER TABLE venue_usps DISABLE ROW LEVEL SECURITY;
ALTER TABLE venue_seasonal_content DISABLE ROW LEVEL SECURITY;
ALTER TABLE voice_preferences DISABLE ROW LEVEL SECURITY;
ALTER TABLE voice_training_sessions DISABLE ROW LEVEL SECURITY;
ALTER TABLE voice_training_responses DISABLE ROW LEVEL SECURITY;
ALTER TABLE learned_preferences DISABLE ROW LEVEL SECURITY;
ALTER TABLE api_costs DISABLE ROW LEVEL SECURITY;
ALTER TABLE trend_recommendations DISABLE ROW LEVEL SECURITY;
ALTER TABLE source_attribution DISABLE ROW LEVEL SECURITY;
ALTER TABLE consultant_metrics DISABLE ROW LEVEL SECURITY;
ALTER TABLE marketing_spend DISABLE ROW LEVEL SECURITY;
ALTER TABLE intelligence_extractions DISABLE ROW LEVEL SECURITY;

-- Migration 009 tables
ALTER TABLE bar_planning DISABLE ROW LEVEL SECURITY;
ALTER TABLE bar_recipes DISABLE ROW LEVEL SECURITY;
ALTER TABLE bar_shopping_list DISABLE ROW LEVEL SECURITY;
ALTER TABLE ceremony_order DISABLE ROW LEVEL SECURITY;
ALTER TABLE makeup_schedule DISABLE ROW LEVEL SECURITY;
ALTER TABLE shuttle_schedule DISABLE ROW LEVEL SECURITY;
ALTER TABLE rehearsal_dinner DISABLE ROW LEVEL SECURITY;
ALTER TABLE decor_inventory DISABLE ROW LEVEL SECURITY;
ALTER TABLE staffing_assignments DISABLE ROW LEVEL SECURITY;
ALTER TABLE bedroom_assignments DISABLE ROW LEVEL SECURITY;
ALTER TABLE allergy_registry DISABLE ROW LEVEL SECURITY;
ALTER TABLE guest_care_notes DISABLE ROW LEVEL SECURITY;
ALTER TABLE wedding_worksheets DISABLE ROW LEVEL SECURITY;
ALTER TABLE wedding_party DISABLE ROW LEVEL SECURITY;
ALTER TABLE photo_library DISABLE ROW LEVEL SECURITY;
ALTER TABLE borrow_catalog DISABLE ROW LEVEL SECURITY;
ALTER TABLE borrow_selections DISABLE ROW LEVEL SECURITY;
ALTER TABLE accommodations DISABLE ROW LEVEL SECURITY;
ALTER TABLE onboarding_progress DISABLE ROW LEVEL SECURITY;
ALTER TABLE section_finalisations DISABLE ROW LEVEL SECURITY;
ALTER TABLE guest_tags DISABLE ROW LEVEL SECURITY;
ALTER TABLE guest_tag_assignments DISABLE ROW LEVEL SECURITY;
ALTER TABLE guest_meal_options DISABLE ROW LEVEL SECURITY;
ALTER TABLE wedding_website_settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE tours DISABLE ROW LEVEL SECURITY;
ALTER TABLE lost_deals DISABLE ROW LEVEL SECURITY;
ALTER TABLE campaigns DISABLE ROW LEVEL SECURITY;
ALTER TABLE social_posts DISABLE ROW LEVEL SECURITY;
ALTER TABLE annotations DISABLE ROW LEVEL SECURITY;
ALTER TABLE venue_health DISABLE ROW LEVEL SECURITY;
ALTER TABLE client_match_queue DISABLE ROW LEVEL SECURITY;
ALTER TABLE knowledge_gaps DISABLE ROW LEVEL SECURITY;
ALTER TABLE follow_up_sequence_templates DISABLE ROW LEVEL SECURITY;
ALTER TABLE wedding_sequences DISABLE ROW LEVEL SECURITY;
ALTER TABLE relationships DISABLE ROW LEVEL SECURITY;
ALTER TABLE client_codes DISABLE ROW LEVEL SECURITY;
ALTER TABLE error_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE notification_tokens DISABLE ROW LEVEL SECURITY;

-- Migration 010-011 tables
ALTER TABLE activity_log DISABLE ROW LEVEL SECURITY;
ALTER TABLE admin_notifications DISABLE ROW LEVEL SECURITY;
