-- seed-contracts-demo.sql
--
-- W57. Two generated contracts on Crestwood Farm so the fifth section on
-- /portal/weddings/<id> shows a real status trail rather than an empty
-- state, and so the couple's own contract list shows the signing pill
-- next to their uploads.
--
-- Both sit on 44444444-…-444444000209 (Crestwood Farm, booked, June 2026,
-- Taylor Kim and Jordan Park), which is the one Crestwood booking in
-- supabase/seed.sql that has people rows with an email on them. The story
-- is the ordinary one: a contract went out in November and was signed, the
-- guest count moved in the spring, so a second one went out and is sitting
-- unsigned.
--
-- Nothing here creates a venue, a wedding or a person.
--
-- Kept out of seed.sql on purpose, the same way seed-commitments-demo.sql
-- is. That file is 2,400 lines and several workstreams edit it; this is a
-- self-contained block that can be run, re-run or dropped on its own.
--
-- Requires migration 409. Idempotent: both inserts are guarded on the id.
--
-- Run:  psql < supabase/seed-contracts-demo.sql
--       (or paste into the Supabase SQL editor)
--
-- ---------------------------------------------------------------------------
-- Two things to know before reading the JSON below
-- ---------------------------------------------------------------------------
--
-- 1. The money in `generated_from` is in integer cents, which is the Bloom
--    convention for weddings.booking_value and friends. The seeded wedding
--    row carries 8800 in that column, which was written as dollars, so
--    pressing "Build a contract" on this wedding in the demo renders $88
--    rather than $8,800. That is a pre-existing seed problem, not a
--    contract one, and it is not fixed here because supabase/seed.sql is
--    shared. The frozen snapshots below carry the figure the demo should
--    show.
--
-- 2. The unsigned contract's `sign_token` is the sha256 of
--        a1b2c3d4e5f60718293a4b5c6d7e8f90
--    so the signing page can actually be opened in a demo, at
--        /join/contract/a1b2c3d4e5f60718293a4b5c6d7e8f90
--    A real token is never written down anywhere; this one is in a seed
--    file on purpose and must never be used for anything but the demo
--    venues.
--
-- 3. `generated_from` here carries only the snapshot, no `template` key.
--    That is a valid shape: a row with no frozen template falls back to
--    the standard wording, which is what these two were sent with anyway.
--    A contract generated by the app writes both.
-- ---------------------------------------------------------------------------

-- ---------------------------------------------------------------------------
-- 1. The signed one. Went out in November, signed two days later.
-- ---------------------------------------------------------------------------

INSERT INTO public.contracts (
  id, venue_id, wedding_id, filename, file_type, storage_path,
  extracted_text, kind, status, template_key, generated_from,
  sent_at, viewed_at, signed_at, signed_name, signed_ip, created_at
)
SELECT
  'c0117ac7-0000-0000-0000-000000000001',
  '22222222-2222-2222-2222-222222222202',
  '44444444-4444-4444-4444-444444000209',
  'CW-2606-06-agreement.pdf',
  'pdf',
  '44444444-4444-4444-4444-444444000209/1762000000000_CW-2606-06-agreement.pdf',
  'Wedding agreement. This is the agreement between Taylor Kim and Jordan Park and Crestwood Farm for a wedding on Saturday, 6 June 2026.',
  'generated',
  'signed',
  'standard',
  jsonb_build_object(
    'snapshot', jsonb_build_object(
      'venueName', 'Crestwood Farm',
      'coordinatorName', 'Maya Rodriguez',
      'coordinatorEmail', 'maya@crestwoodfarm.test',
      'coordinatorPhone', NULL,
      'currency', 'USD',
      'coupleNames', 'Taylor Kim and Jordan Park',
      'weddingDate', '2026-06-06',
      'eventCode', 'CW-2606-06',
      'guestCount', 110,
      'packageName', 'Saturday Full Day',
      'totalCents', 880000,
      'depositCents', 200000,
      'paidCents', 200000,
      'taxCents', NULL,
      'gratuityCents', NULL,
      'checkIn', '10:00am on the Friday',
      'checkOut', '11:00am on the Sunday',
      'weddingHours', '8 hours',
      'rehearsalHours', '2 hours',
      'maxWeddingGuests', 150,
      'maxRehearsalGuests', 40,
      'overnights', 2,
      'generatedAt', '2025-11-03T15:00:00Z'
    )
  ),
  '2025-11-03T15:12:00Z',
  '2025-11-03T19:44:00Z',
  '2025-11-05T09:21:00Z',
  'Taylor Kim',
  '203.0.113.24',
  '2025-11-03T15:00:00Z'
WHERE NOT EXISTS (
  SELECT 1 FROM public.contracts WHERE id = 'c0117ac7-0000-0000-0000-000000000001'
);

-- ---------------------------------------------------------------------------
-- 2. The one still waiting. Guest count went from 110 to 130 in the
--    spring, so a second contract went out and has not been signed.
--    Opened once, not agreed to, which is the state a coordinator most
--    wants to see on the page. Status is 'viewed' rather than 'sent'
--    because viewed_at is set; the two move together.
-- ---------------------------------------------------------------------------

INSERT INTO public.contracts (
  id, venue_id, wedding_id, filename, file_type, storage_path,
  extracted_text, kind, status, template_key, generated_from,
  sign_token, sent_at, viewed_at, created_at
)
SELECT
  'c0117ac7-0000-0000-0000-000000000002',
  '22222222-2222-2222-2222-222222222202',
  '44444444-4444-4444-4444-444444000209',
  'CW-2606-06-agreement.pdf',
  'pdf',
  '44444444-4444-4444-4444-444444000209/1773000000000_CW-2606-06-agreement.pdf',
  'Wedding agreement. This is the agreement between Taylor Kim and Jordan Park and Crestwood Farm for a wedding on Saturday, 6 June 2026. Guests: up to 130.',
  'generated',
  'viewed',
  'standard',
  jsonb_build_object(
    'snapshot', jsonb_build_object(
      'venueName', 'Crestwood Farm',
      'coordinatorName', 'Maya Rodriguez',
      'coordinatorEmail', 'maya@crestwoodfarm.test',
      'coordinatorPhone', NULL,
      'currency', 'USD',
      'coupleNames', 'Taylor Kim and Jordan Park',
      'weddingDate', '2026-06-06',
      'eventCode', 'CW-2606-06',
      'guestCount', 130,
      'packageName', 'Saturday Full Day',
      'totalCents', 960000,
      'depositCents', 200000,
      'paidCents', 480000,
      'taxCents', NULL,
      'gratuityCents', NULL,
      'checkIn', '10:00am on the Friday',
      'checkOut', '11:00am on the Sunday',
      'weddingHours', '8 hours',
      'rehearsalHours', '2 hours',
      'maxWeddingGuests', 150,
      'maxRehearsalGuests', 40,
      'overnights', 2,
      'generatedAt', '2026-03-09T11:00:00Z'
    )
  ),
  'ff25d2389ab7917a77cc0c3546331401054d53cb7b2edeedb7b4e7742bb5286d',
  '2026-03-09T11:05:00Z',
  '2026-03-09T20:18:00Z',
  '2026-03-09T11:00:00Z'
WHERE NOT EXISTS (
  SELECT 1 FROM public.contracts WHERE id = 'c0117ac7-0000-0000-0000-000000000002'
);
