-- ===========================================================================
-- APPLY-WAVES-27-29-AND-FIXES.sql  (regenerated 2026-05-11, third pass)
-- ===========================================================================
-- Schema fixes from prior apply attempts (all corrected in-place):
--   • Mig 293: dropped join on drafts.sent_interaction_id (no such column).
--   • Mig 295: venue_members → user_profiles (correct scoping pattern).
--   • Mig 296: profiles + venue_members → user_profiles with real role
--     enum values (super_admin / org_admin / venue_manager).
--   • Mig 298: coerces existing non-conforming category values to 'other'
--     BEFORE adding CHECK (existing rows had values outside the enum).
--   • Mig 301: contacts uses `type` + `value`, not contact_type /
--     contact_value.
--
-- Every statement is idempotent. Safe to re-run after a partial apply.
-- ===========================================================================


-- ---------------------------------------------------------------------------
-- 293_interactions_author_class.sql  (Wave 27)
-- ---------------------------------------------------------------------------
-- Adds the third dimension to interactions: WHO authored the signal.
--
-- The platform already has:
--   - direction (inbound / outbound) — which way the message flows
--   - type (email / call / voicemail / sms / meeting / web_form) — what shape
--   - signal_class (source / touchpoint / crm / outcome / unclassified) — its role
--
-- Missing: author_class — who actually composed the content. A Calendly
-- notification ("Sarah Smith booked a tour") is direction=inbound type=email
-- but the AUTHOR is Calendly's system, not Sarah. Today downstream consumers
-- (knowledge-gap detector, classifier health metric, heat scoring, draft
-- training) can't tell those apart from real couple messages — they
-- contaminate every metric they touch.
--
-- author_class values:
--   couple           — written by a couple/lead (the canonical case)
--   operator         — written by venue staff (Isadora, coordinator)
--   sage             — generated by the AI agent (Sage / venue-specific name)
--   platform_system  — automated email from Calendly, Knot relay, HoneyBook,
--                      autoresponder, OOO reply, mailchimp campaign, etc.
--   vendor           — written by a wedding vendor (photographer, florist)
--   unknown          — pipeline could not classify (DEFAULT)
--
-- Default 'unknown' is intentional. The Haiku classifier in
-- src/lib/services/email/author-classifier.ts runs at write time and
-- updates the row; existing rows are backfilled by the cron job.
-- ---------------------------------------------------------------------------

ALTER TABLE interactions
  ADD COLUMN IF NOT EXISTS author_class TEXT NOT NULL DEFAULT 'unknown';

ALTER TABLE interactions DROP CONSTRAINT IF EXISTS interactions_author_class_check;
ALTER TABLE interactions
  ADD CONSTRAINT interactions_author_class_check
  CHECK (author_class IN ('couple', 'operator', 'sage', 'platform_system', 'vendor', 'unknown'));

-- Tracks which prompt version classified the row, so when we bump the
-- author-class prompt we can re-classify only what's stale.
ALTER TABLE interactions
  ADD COLUMN IF NOT EXISTS author_class_prompt_version TEXT;

ALTER TABLE interactions
  ADD COLUMN IF NOT EXISTS author_class_decided_at TIMESTAMPTZ;

-- Outbound rows backfill as 'operator' synchronously. The Haiku classifier
-- (author-classifier.ts) later upgrades to 'sage' when it detects the AI-
-- disclosure footer in the body — which is the actual ground-truth signal
-- for "this was Sage-authored" anyway. drafts does not carry a direct FK
-- to the resulting outbound interaction, so we don't try to do that join
-- here. The Haiku pass handles the refinement.
UPDATE interactions
SET author_class = 'operator',
    author_class_prompt_version = 'rules-v1',
    author_class_decided_at = NOW()
WHERE direction = 'outbound'
  AND author_class = 'unknown';

-- Index used by the backfill cron + the classifier-health metric to find
-- inbound rows still pending classification.
CREATE INDEX IF NOT EXISTS idx_interactions_author_class_pending
  ON interactions (venue_id, author_class)
  WHERE author_class = 'unknown' AND direction = 'inbound';

COMMENT ON COLUMN interactions.author_class IS
  'Wave 27: who authored this signal. Defaults to unknown; Haiku classifier sets to couple/operator/sage/platform_system/vendor at write time. Backfill cron handles legacy rows.';

NOTIFY pgrst, 'reload schema';
-- ---------------------------------------------------------------------------
-- 294_interactions_surface.sql  (Wave 28)
-- ---------------------------------------------------------------------------
-- Adds the fourth dimension to interactions: WHERE this signal should appear.
--
-- The /agent/inbox surface today shows every type='email' direction='inbound'
-- row. That includes:
--   - HoneyBook synthetic interactions (source_provenance attribution from
--     CRM import) → should appear on lead-detail timeline, NOT in inbox
--   - Calendly tour-confirmation emails ("Sarah Smith booked a tour") →
--     should appear on lead-detail timeline, NOT in inbox
--   - Knot/WeddingWire/Zola lead-relay alerts → could go either way; for
--     now we leave them in inbox since the operator may want to triage
--
-- surface values:
--   inbox                — couple-facing conversation thread (DEFAULT)
--   system_notification  — automated email from a SaaS tool (Calendly,
--                          HoneyBook, autoresponder)
--   crm_attribution      — synthetic interaction from a CRM import adapter
--                          (HoneyBook, Dubsado, Aisle Planner sync rows)
--   voice_capture        — Omi/Plaud/SMS transcript appears in /agent/audio-inbox
--   integration_event    — webhook-driven structured event (Calendly booking,
--                          Twilio SMS receipt, Zoom transcript) where the
--                          ROW IS the event, not the email about it
--
-- Default 'inbox' preserves existing UI behavior for every row that doesn't
-- match a rule. Pipeline write site + CRM adapters set surface explicitly
-- for known cases.
-- ---------------------------------------------------------------------------

ALTER TABLE interactions
  ADD COLUMN IF NOT EXISTS surface TEXT NOT NULL DEFAULT 'inbox';

ALTER TABLE interactions DROP CONSTRAINT IF EXISTS interactions_surface_check;
ALTER TABLE interactions
  ADD CONSTRAINT interactions_surface_check
  CHECK (surface IN ('inbox', 'system_notification', 'crm_attribution', 'voice_capture', 'integration_event'));

-- ---------------------------------------------------------------------------
-- Backfill rules (rules-based, no AI call — these are structural).
-- ---------------------------------------------------------------------------

-- CRM import rows: every interaction with a non-null crm_source flag that
-- was written by an import adapter (vs by the email pipeline) is
-- crm_attribution. The synthetic source-attribution rows that HoneyBook
-- writes (body starts with "provider:honeybook") are the canonical case.
UPDATE interactions
SET surface = 'crm_attribution'
WHERE surface = 'inbox'
  AND crm_source IS NOT NULL
  AND (
    full_body LIKE 'provider:%'
    OR subject IS NULL
  );

-- Calendly system emails — direction=inbound, type=email, from-domain matches
-- Calendly's sending addresses. The actual tour booking is captured as a
-- separate engagement_events row + tours row by the Calendly webhook; the
-- email is duplicate UI clutter.
UPDATE interactions
SET surface = 'system_notification'
WHERE surface = 'inbox'
  AND type = 'email'
  AND direction = 'inbound'
  AND (
    from_email ILIKE '%@calendly.com'
    OR from_email ILIKE '%@acuityscheduling.com'
    OR from_email ILIKE 'notifications@honeybook.com'
    OR from_email ILIKE 'no-reply@%'
    OR from_email ILIKE 'noreply@%'
    OR from_email ILIKE 'donotreply@%'
  );

-- Voice capture: Omi/Plaud transcripts already write type='meeting' with
-- a specific source_context. Stream 3 will land Twilio SMS + Zoom; this
-- migration just claims the surface for existing audio rows.
UPDATE interactions
SET surface = 'voice_capture'
WHERE surface = 'inbox'
  AND type IN ('voicemail', 'meeting')
  AND (
    crm_source IS NULL
    OR crm_source NOT IN ('honeybook', 'dubsado', 'aisle_planner', 'generic_csv')
  );

-- Index used by the inbox query (the main consumer of this column).
CREATE INDEX IF NOT EXISTS idx_interactions_surface_inbox
  ON interactions (venue_id, surface, direction, timestamp DESC)
  WHERE surface = 'inbox';

COMMENT ON COLUMN interactions.surface IS
  'Wave 28: where this signal should appear in the UI. Defaults to inbox; pipeline + CRM adapters route system_notification / crm_attribution / voice_capture / integration_event explicitly.';

NOTIFY pgrst, 'reload schema';
-- ---------------------------------------------------------------------------
-- 295_multichannel_inbox_support.sql  (Wave 29)
-- ---------------------------------------------------------------------------
-- Schema affordances for SMS + Zoom ingestion. The interactions.type CHECK
-- already supports 'sms' (mig 178) and 'meeting' (mig 100) — Zoom transcripts
-- ride on 'meeting'. This migration only adds the operational tables:
--
--   1. twilio_webhook_log — every Twilio webhook hits this table first
--      (idempotency log). Per-venue scoped via phone_number.
--   2. zoom_webhook_log — analogous for Zoom.
--   3. multi_channel_inbox_settings — per-venue config (which channels are
--      enabled, what phone numbers / Zoom accounts to listen to).
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS twilio_webhook_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  venue_id UUID REFERENCES venues(id) ON DELETE CASCADE,
  message_sid TEXT NOT NULL,
  from_phone TEXT,
  to_phone TEXT,
  body TEXT,
  num_media INTEGER DEFAULT 0,
  raw_payload JSONB,
  interaction_id UUID REFERENCES interactions(id) ON DELETE SET NULL,
  processed_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (message_sid)
);

CREATE INDEX IF NOT EXISTS idx_twilio_webhook_log_venue
  ON twilio_webhook_log (venue_id, created_at DESC);

CREATE TABLE IF NOT EXISTS zoom_webhook_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  venue_id UUID REFERENCES venues(id) ON DELETE CASCADE,
  meeting_uuid TEXT NOT NULL,
  event_type TEXT,
  topic TEXT,
  host_email TEXT,
  start_time TIMESTAMPTZ,
  duration_minutes INTEGER,
  recording_url TEXT,
  transcript_url TEXT,
  raw_payload JSONB,
  interaction_id UUID REFERENCES interactions(id) ON DELETE SET NULL,
  processed_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (meeting_uuid, event_type)
);

CREATE INDEX IF NOT EXISTS idx_zoom_webhook_log_venue
  ON zoom_webhook_log (venue_id, start_time DESC);

CREATE TABLE IF NOT EXISTS multi_channel_inbox_settings (
  venue_id UUID PRIMARY KEY REFERENCES venues(id) ON DELETE CASCADE,
  sms_enabled BOOLEAN DEFAULT false,
  twilio_phone_numbers TEXT[] DEFAULT '{}',
  zoom_enabled BOOLEAN DEFAULT false,
  zoom_account_emails TEXT[] DEFAULT '{}',
  voice_capture_enabled BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS: scope reads to the venue's own settings.
ALTER TABLE twilio_webhook_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE zoom_webhook_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE multi_channel_inbox_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS twilio_webhook_log_venue_read ON twilio_webhook_log;
CREATE POLICY twilio_webhook_log_venue_read ON twilio_webhook_log
  FOR SELECT USING (
    venue_id = (SELECT venue_id FROM user_profiles WHERE id = auth.uid())
  );

DROP POLICY IF EXISTS zoom_webhook_log_venue_read ON zoom_webhook_log;
CREATE POLICY zoom_webhook_log_venue_read ON zoom_webhook_log
  FOR SELECT USING (
    venue_id = (SELECT venue_id FROM user_profiles WHERE id = auth.uid())
  );

DROP POLICY IF EXISTS mci_settings_venue_rw ON multi_channel_inbox_settings;
CREATE POLICY mci_settings_venue_rw ON multi_channel_inbox_settings
  FOR ALL USING (
    venue_id = (SELECT venue_id FROM user_profiles WHERE id = auth.uid())
  );

NOTIFY pgrst, 'reload schema';
-- ---------------------------------------------------------------------------
-- 296_api_costs_rls_hardening.sql  (Tactical: F19)
-- ---------------------------------------------------------------------------
-- The /agent/classification-health page reads api_costs to compute the
-- Sage-cost panel. Today the table may be readable by any authenticated
-- user. F19 flags that non-admin operators see AI cost data they shouldn't.
--
-- Scope: SELECT restricted to super_admin OR venue_owner. Non-admin
-- coordinators see classification health (counts only) but not the cost.
-- ---------------------------------------------------------------------------

ALTER TABLE api_costs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS api_costs_admin_read ON api_costs;
CREATE POLICY api_costs_admin_read ON api_costs
  FOR SELECT USING (
    -- Super-admin (Bloom platform staff) sees everything across venues.
    EXISTS (
      SELECT 1 FROM user_profiles
      WHERE user_profiles.id = auth.uid()
        AND user_profiles.role = 'super_admin'
    )
    OR
    -- Admin-tier roles on the matching venue see their own venue's costs.
    -- user_profiles.role enum per 001_shared_tables: ('super_admin',
    -- 'org_admin', 'venue_manager', 'coordinator', 'couple'). The first
    -- three are the admin tier; coordinator is excluded so reception-style
    -- users don't see $ amounts.
    venue_id = (
      SELECT venue_id FROM user_profiles
      WHERE id = auth.uid()
        AND role IN ('super_admin', 'org_admin', 'venue_manager')
    )
  );

-- INSERT/UPDATE policies remain service-role only — api_costs is
-- written by the cost-tracker (lib/ai/cost-tracker.ts), never by
-- client UI.
DROP POLICY IF EXISTS api_costs_service_write ON api_costs;
CREATE POLICY api_costs_service_write ON api_costs
  FOR INSERT
  WITH CHECK (
    auth.role() = 'service_role'
  );

COMMENT ON POLICY api_costs_admin_read ON api_costs IS
  'F19: AI cost data restricted to super_admin or venue owner/admin. Coordinator role does not see $ figures on /agent/classification-health.';

NOTIFY pgrst, 'reload schema';
-- ---------------------------------------------------------------------------
-- 297_sequence_triggers_extension.sql  (F12)
-- ---------------------------------------------------------------------------
-- The sequences table currently accepts only post_tour / ghosted /
-- post_booking / pre_event / custom. Operators have asked for trigger
-- types that fire on real lifecycle events the platform already detects:
--
--   tour_cancelled      — tour scheduled then cancelled (re-engagement)
--   lost_reactivation   — wedding marked lost N days ago (cold revival)
--   no_show             — tour scheduled, did not happen, no cancellation
--   contract_overdue    — proposal_sent → no signed contract by deadline
--
-- These map to state-machine signals the platform already emits — the
-- sequence runner just needs to know to fire on them.
-- ---------------------------------------------------------------------------

-- Real table name is follow_up_sequences (mig 025), not sequences.
ALTER TABLE follow_up_sequences DROP CONSTRAINT IF EXISTS follow_up_sequences_trigger_type_check;
ALTER TABLE follow_up_sequences DROP CONSTRAINT IF EXISTS sequences_trigger_type_check;
ALTER TABLE follow_up_sequences
  ADD CONSTRAINT follow_up_sequences_trigger_type_check
  CHECK (trigger_type IN (
    'post_tour',
    'ghosted',
    'post_booking',
    'pre_event',
    'tour_cancelled',
    'lost_reactivation',
    'no_show',
    'contract_overdue',
    'custom'
  ));

NOTIFY pgrst, 'reload schema';
-- ---------------------------------------------------------------------------
-- 298_knowledge_gaps_category_required.sql  (F22)
-- ---------------------------------------------------------------------------
-- The Wave 19 detector validator requires `category` ∈ {pricing, availability,
-- logistics, policy, vendor, ceremony, catering, inclusions, other}, but the
-- manual-capture API route (/api/admin/knowledge-gaps/capture) allows rows
-- with NULL category. Result: the /agent/knowledge-gaps page filters by
-- category and 447 legacy rows show as "uncategorized" with no path forward.
--
-- This migration:
--   1. Tags every NULL-category row with 'other' so the UI can render them.
--      A separate Haiku backfill (Stream 4) will re-categorize 'other' rows
--      against real content over the next cron tick.
--   2. Adds the CHECK constraint to prevent future NULL writes.
-- ---------------------------------------------------------------------------

-- Step 1: coerce ALL non-conforming values to 'other'. The original
-- knowledge_gaps schema (mig 009) had `category text` with NO check,
-- so historical rows carry whatever string the pre-Wave-19 writers
-- chose ('general', 'misc', 'follow_up', null, …). Coercing to 'other'
-- means the new CHECK can land without violation; the Haiku re-
-- categoriser (knowledge-gaps/category-backfill.ts) will upgrade
-- 'other' rows to real categories on the next cron tick.
UPDATE knowledge_gaps
SET category = 'other'
WHERE category IS NULL
   OR category NOT IN (
     'pricing',
     'availability',
     'logistics',
     'policy',
     'vendor',
     'ceremony',
     'catering',
     'inclusions',
     'other'
   );

-- Step 2: enforce CHECK + NOT NULL going forward.
ALTER TABLE knowledge_gaps
  ALTER COLUMN category SET NOT NULL;

ALTER TABLE knowledge_gaps DROP CONSTRAINT IF EXISTS knowledge_gaps_category_check;
ALTER TABLE knowledge_gaps
  ADD CONSTRAINT knowledge_gaps_category_check
  CHECK (category IN (
    'pricing',
    'availability',
    'logistics',
    'policy',
    'vendor',
    'ceremony',
    'catering',
    'inclusions',
    'other'
  ));

-- Index for the UI filter (open + by category).
CREATE INDEX IF NOT EXISTS idx_knowledge_gaps_venue_status_category
  ON knowledge_gaps (venue_id, status, category)
  WHERE status = 'open';

NOTIFY pgrst, 'reload schema';
-- ---------------------------------------------------------------------------
-- 299_venue_ai_reviewer_intro.sql  (live-customer fix 2026-05-11)
-- ---------------------------------------------------------------------------
-- Adds `venue_ai_config.reviewer_intro` — a short operator-authored phrase
-- the disclosure footer renders so the email reads warm + accountable
-- instead of clinical. For Rixey Isadora would set:
--   "Based on Isadora's thinking. She double-checks the important details
--    before anything goes out."
--
-- When NULL the footer falls back to a safe generic line so unconfigured
-- venues still ship a valid disclosure.
-- ---------------------------------------------------------------------------

ALTER TABLE venue_ai_config
  ADD COLUMN IF NOT EXISTS reviewer_intro TEXT;

COMMENT ON COLUMN venue_ai_config.reviewer_intro IS
  'Operator-authored short phrase rendered in the Sage disclosure footer ("Based on Isadora''s thinking. She double-checks the important details."). NULL falls back to "Reviewed by the team before anything important goes out."';

NOTIFY pgrst, 'reload schema';
-- ---------------------------------------------------------------------------
-- 300_interactions_disclosure_and_escalation.sql  (deep fix 2026-05-11)
-- ---------------------------------------------------------------------------
-- Two columns to move idempotency + escalation state off the email body
-- and onto the row where they belong:
--
-- 1. disclosure_version — replaces the in-body `[sage-ai-disclosure-vN]`
--    marker that was leaking as visible text to recipients (a couple read
--    it and was understandably put off). The marker was used purely for
--    idempotency: "did we already append the footer to this body?". With
--    a column the footer body stays clean and the row carries the version
--    stamp.
--
-- 2. escalation_requested — set when the inbound carries a human-escalation
--    request (legacy "HUMAN REQUESTED" magic-words OR the broader Haiku
--    classifier's verdict). Surfaces in the inbox folder + auto-skips
--    drafting + fires admin_notifications. Today the pipeline detects
--    this only via regex on subject; the column lets every downstream
--    consumer (heat scoring, knowledge-gaps detector, classifier health)
--    skip these rows uniformly.
-- ---------------------------------------------------------------------------

ALTER TABLE interactions
  ADD COLUMN IF NOT EXISTS disclosure_version TEXT;

ALTER TABLE interactions DROP CONSTRAINT IF EXISTS interactions_disclosure_version_check;
ALTER TABLE interactions
  ADD CONSTRAINT interactions_disclosure_version_check
  CHECK (
    disclosure_version IS NULL
    OR disclosure_version IN ('v1', 'v2', 'v3', 'v4')
  );

ALTER TABLE interactions
  ADD COLUMN IF NOT EXISTS escalation_requested BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE interactions
  ADD COLUMN IF NOT EXISTS escalation_reason TEXT;

ALTER TABLE interactions DROP CONSTRAINT IF EXISTS interactions_escalation_reason_check;
ALTER TABLE interactions
  ADD CONSTRAINT interactions_escalation_reason_check
  CHECK (
    escalation_reason IS NULL
    OR escalation_reason IN ('magic_words', 'haiku_detected', 'operator_flagged')
  );

ALTER TABLE interactions
  ADD COLUMN IF NOT EXISTS escalation_decided_at TIMESTAMPTZ;

-- Backfill: any existing row whose body contains a legacy disclosure marker
-- gets its row-level disclosure_version stamped so future writes skip the
-- re-append. v3 is the most common; check it first to short-circuit.
UPDATE interactions
SET disclosure_version = 'v3'
WHERE disclosure_version IS NULL
  AND direction = 'outbound'
  AND full_body LIKE '%[sage-ai-disclosure-v3]%';

UPDATE interactions
SET disclosure_version = 'v2'
WHERE disclosure_version IS NULL
  AND direction = 'outbound'
  AND full_body LIKE '%[sage-ai-disclosure-v2]%';

UPDATE interactions
SET disclosure_version = 'v1'
WHERE disclosure_version IS NULL
  AND direction = 'outbound'
  AND full_body LIKE '%[sage-ai-disclosure-v1]%';

-- Index used by the inbox / classifier-health consumers to skip
-- escalated rows uniformly.
CREATE INDEX IF NOT EXISTS idx_interactions_escalation_requested
  ON interactions (venue_id, escalation_requested, timestamp DESC)
  WHERE escalation_requested = true;

-- ---------------------------------------------------------------------------
-- drafts mirror columns so the operator-facing drafts surface can show the
-- "address unreachable" + "escalation requested" states without joining
-- back to interactions on every render.
-- ---------------------------------------------------------------------------

ALTER TABLE drafts
  ADD COLUMN IF NOT EXISTS needs_real_address BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE drafts
  ADD COLUMN IF NOT EXISTS escalation_requested BOOLEAN NOT NULL DEFAULT false;

COMMENT ON COLUMN interactions.disclosure_version IS
  '2026-05-11: row-level disclosure version stamp. Replaces the in-body marker that was leaking as visible text. NULL = no footer ever appended (inbound or legacy outbound).';

COMMENT ON COLUMN interactions.escalation_requested IS
  '2026-05-11: true when the inbound carries a human-escalation request. Routed by detectHumanEscalation (regex fast-path) or the Haiku escalation classifier. Pipeline skips drafting + fires admin_notifications; downstream consumers filter these out.';

COMMENT ON COLUMN drafts.needs_real_address IS
  '2026-05-11: draft targets an unroutable synthetic / .invalid address (e.g. WeddingWire relay token). Auto-send refuses; operator must resolve a real address before sending.';

NOTIFY pgrst, 'reload schema';
-- ---------------------------------------------------------------------------
-- 301_unroutable_address_backfill.sql  (live-customer fix 2026-05-11)
-- ---------------------------------------------------------------------------
-- Companion to the form-relay-parsers fix + isUnsendableAddress helper
-- shipped 2026-05-11. Historically, when listing platforms didn't expose
-- a routable per-prospect identifier, parsers anchored leads on either:
--
--   1. A Bloom-synthesised placeholder (e.g. WeddingWire's
--      `authsolic-{token}@weddingwire.bloom-relay.invalid`)
--   2. A no-reply / system-only local part the venue's own infra emitted
--   3. An RFC-2606 reserved TLD (`.invalid`, `.test`, `.example`,
--      `.localhost`) some integration test or import script slipped in
--
-- The autonomous sender + manual /agent/send + /agent/reply paths used
-- those addresses as the To: header. Gmail returned hard bounces
-- ("Address not found"), no-reply senders silently dropped replies.
--
-- The fix re-prioritises per-prospect routable relays
-- (`user-{token}@reply.weddingwire.com`, `<prospect>.<slug>@member.
-- theknot.com`, `connect-{uuid}@zola.com`) and the personal email
-- where available. This migration backfills historical rows so
-- existing leads can be replied to.
--
-- Strategy: find each person whose canonical email is unroutable, look
-- up the matching wedding's most recent inbound interaction with a
-- routable from_email, and promote that address. Original unroutable
-- value preserved in people.extracted_identity for audit.
--
-- All operations are idempotent: re-running is a no-op because the WHERE
-- clause filters rows whose email is still unroutable.
-- ---------------------------------------------------------------------------

-- Reusable: predicate for "is this email unroutable for send".
-- Mirrors the TS `isUnsendableAddress` helper. Coverage:
--   - RFC 2606 reserved TLDs (.invalid / .test / .example / .localhost)
--   - RFC 2606 reserved second-level (example.com / .net / .org)
--   - No-reply / system-only local parts
-- We use the predicate inline (no PL/pgSQL function) so the migration
-- stays statement-level idempotent per the exec_sql RPC contract.

-- Reusable: predicate for "is this a per-prospect routable relay".
-- Mirrors the TS `isPerProspectRelay` helper.

-- Step 1: build a temp mapping table.
-- For each person whose canonical email is unroutable, find a routable
-- replacement from the most recent inbound interaction on the same
-- wedding. Routable = either a personal email (not in any platform's
-- relay domain) or a per-prospect relay shape.
CREATE TEMP TABLE IF NOT EXISTS _unroutable_addr_backfill_map AS
SELECT DISTINCT ON (p.id)
  p.id              AS person_id,
  p.venue_id,
  p.wedding_id,
  p.email           AS unroutable_email,
  i.from_email      AS routable_email
FROM people p
JOIN interactions i
  ON i.wedding_id = p.wedding_id
 AND i.venue_id = p.venue_id
 AND i.direction = 'inbound'
 -- Candidate routable addresses: per-prospect relay shapes OR addresses
 -- that don't match any unsendable predicate. Excludes shared-relay
 -- forms (leads@*, messages@*) by negative match on no-reply locals
 -- + by the parser-level skip that already prevents new shared-relay
 -- leads. For historical rows we accept the broadest "not unsendable"
 -- test below.
 AND i.from_email IS NOT NULL
 AND i.from_email !~* '\.(invalid|test|example|localhost)$'
 AND i.from_email !~* '@(example\.com|example\.net|example\.org)$'
 AND lower(split_part(i.from_email, '@', 1)) NOT IN (
   'noreply', 'no-reply', 'donotreply', 'do-not-reply', 'do_not_reply',
   'mailer-daemon', 'mailerdaemon', 'postmaster',
   'bounce', 'bounces', 'unsubscribe'
 )
 AND i.from_email ~* '@'
WHERE
  -- person's canonical email is unsendable in any of the ways we care about
  (
    p.email ~* '\.(invalid|test|example|localhost)$'
    OR p.email ~* '@(example\.com|example\.net|example\.org)$'
    OR lower(split_part(p.email, '@', 1)) IN (
      'noreply', 'no-reply', 'donotreply', 'do-not-reply', 'do_not_reply',
      'mailer-daemon', 'mailerdaemon', 'postmaster',
      'bounce', 'bounces', 'unsubscribe'
    )
  )
ORDER BY p.id, i.timestamp DESC;

-- Step 2: promote the routable email to people.email. Preserve the
-- unroutable original in extracted_identity for audit lineage.
UPDATE people p
SET
  email = m.routable_email,
  extracted_identity =
    COALESCE(p.extracted_identity, '{}'::jsonb)
    || jsonb_build_object(
      'historical_unroutable_email', m.unroutable_email,
      'address_backfill_at', NOW()::text
    )
FROM _unroutable_addr_backfill_map m
WHERE p.id = m.person_id;

-- Step 3: same for contacts. The contacts table is the canonical
-- multi-channel address store; people.email is a denormalised cache.
-- Both need to flip for the send paths to find the right address.
-- contacts table uses columns `type` + `value` (per 001_shared_tables),
-- not contact_type / contact_value. Fixed 2026-05-11 after live-customer
-- apply attempt surfaced the column-name miss.
UPDATE contacts c
SET value = m.routable_email
FROM _unroutable_addr_backfill_map m
WHERE c.person_id = m.person_id
  AND c.type = 'email'
  AND (
    c.value ~* '\.(invalid|test|example|localhost)$'
    OR c.value ~* '@(example\.com|example\.net|example\.org)$'
    OR lower(split_part(c.value, '@', 1)) IN (
      'noreply', 'no-reply', 'donotreply', 'do-not-reply', 'do_not_reply',
      'mailer-daemon', 'mailerdaemon', 'postmaster',
      'bounce', 'bounces', 'unsubscribe'
    )
  );

-- Step 4: emit a row count summary so the apply script surfaces
-- "N rows backfilled" without a separate query round-trip.
DO $$
DECLARE
  n INTEGER;
BEGIN
  SELECT COUNT(*) INTO n FROM _unroutable_addr_backfill_map;
  RAISE NOTICE 'Unroutable address backfill: % person row(s) promoted', n;
END $$;

DROP TABLE IF EXISTS _unroutable_addr_backfill_map;

NOTIFY pgrst, 'reload schema';
-- ---------------------------------------------------------------------------
-- 302_knowledge_base_source_extension.sql  (live-customer fix 2026-05-11)
-- ---------------------------------------------------------------------------
-- The brain-dump "Send to Sage" path (/api/brain-dump/[id]/resolve) writes
-- knowledge_base rows with source='brain_dump_confirmed' to preserve
-- provenance — but the original CHECK constraint from migration 033 only
-- allowed ('manual', 'auto-learned', 'csv'), so every brain-dump-driven
-- KB insert was failing with:
--
--   new row for relation "knowledge_base" violates check constraint
--   "knowledge_base_source_check"
--
-- Live-customer 2026-05-11: Isadora hit this trying to add a calculator
-- rule note ("when replying to inquiries that submitted a calculator it
-- needs to not assume there are overnights unless overnights are listed
-- on the calculator").
--
-- Fix: extend the CHECK to include 'brain_dump_confirmed'. We also add
-- 'content_suggester' so the Wave 26 / Stream 6 USP + seasonal-content
-- suggester (which doesn't write KB today but plausibly will) has a
-- ready-to-use provenance tag — avoids another constraint extension on
-- the same column in two weeks.
--
-- Provenance values now allowed:
--   manual                — coordinator typed it in /portal/kb
--   auto-learned          — Sage queue resolution promoted Q+A
--   csv                   — bulk CSV import (data-import.ts paths)
--   brain_dump_confirmed  — brain-dump propose-and-confirm flow
--   content_suggester     — Sonnet-suggested entry from venue website
-- ---------------------------------------------------------------------------

ALTER TABLE knowledge_base DROP CONSTRAINT IF EXISTS knowledge_base_source_check;

ALTER TABLE knowledge_base
  ADD CONSTRAINT knowledge_base_source_check
  CHECK (source IN (
    'manual',
    'auto-learned',
    'csv',
    'brain_dump_confirmed',
    'content_suggester'
  ));

COMMENT ON COLUMN knowledge_base.source IS
  'Provenance tag for the KB entry. manual = coordinator typed in /portal/kb. auto-learned = Sage queue resolution. csv = data-import bulk. brain_dump_confirmed = brain-dump propose-and-confirm flow (2026-05-11). content_suggester = Sonnet pull-from-website (Stream 6).';

NOTIFY pgrst, 'reload schema';
