/**
 * Supabase Database Types (Generated)
 *
 * THIS FILE IS AUTO-GENERATED by:
 *   npx supabase gen types typescript --linked > src/lib/supabase/types.generated.ts
 *
 * Regenerate after schema changes via migration.
 * See scripts/check-types-fresh.mjs for freshness validation.
 *
 * Run in CI and in development to keep types in sync with the live schema.
 * This requires SUPABASE_ACCESS_TOKEN for schema introspection.
 */

// Placeholder — regenerate via `npx supabase gen types typescript --linked`
// when the schema changes. This file should contain the full Database type
// union generated by the Supabase CLI, covering all 388+ migration tables.
// Once generated, clients can import from this file to gain full type safety.

export type Database = Record<string, unknown>
