/**
 * Bloom House — Wave 27 author-class prompt (Haiku tier).
 *
 * Anchor docs:
 *   - bloom-constitution.md (forensic identity reconstruction; same
 *     evidence-chain rigor applied to AUTHORSHIP)
 *   - bloom-may10-wave4-8-shipped.md (Haiku is the right tier for
 *     bounded-schema classification at platform-scale volume)
 *   - bloom-may9-llm-vs-template.md (every surface labelled "AI" or
 *     "Sage" is backed by a real callAI; this is the LLM half of the
 *     author-class chokepoint, not a heuristic patch)
 *   - feedback_deep_fix_vs_bandaid.md (author_class is a class-of-
 *     problem dimension — not a Calendly/HoneyBook block-list)
 *
 * What this prompt judges
 * -----------------------
 * Every inbound interaction passes through here. The pipeline pre-
 * classifies outbound rows synchronously (operator vs sage based on
 * direction + auto_sent linkage). Inbound rows arrive at 'unknown'
 * and this Haiku pass replaces that default with the real author.
 *
 *   couple           — the lead/couple themselves
 *   operator         — venue staff (Isadora or coordinator)
 *   sage             — the AI agent (echoed back into the inbox, rare
 *                      for inbound but possible on multi-Gmail venues)
 *   platform_system  — Calendly, Knot relay, HoneyBook notifications,
 *                      autoresponders, OOO replies, mailchimp campaigns
 *   vendor           — wedding vendors (photographer, florist, planner)
 *   unknown          — judge cannot commit (returned only as refusal)
 *
 * Cost target: ~$0.0003 per email on Haiku. At Rixey scale
 * (~12,000 historical interactions backfill) that's ~$3.60 total; at
 * live-pipeline scale (~30 inbounds/day) under $0.01/day. Wedgewood
 * scale (80 venues) under $1/day in author-class spend.
 *
 * Output: ONLY the JSON object.
 */

export const AUTHOR_CLASS_PROMPT_VERSION = 'author-class.prompt.v1'

// ---------------------------------------------------------------------------
// Public types — wire shape the prompt asks for.
// ---------------------------------------------------------------------------

export type AuthorClass =
  | 'couple'
  | 'operator'
  | 'sage'
  | 'platform_system'
  | 'vendor'
  | 'unknown'

export interface AuthorClassOutput {
  author_class: AuthorClass
  reasoning: string
}

// ---------------------------------------------------------------------------
// Evidence input — what the user prompt serialises.
// ---------------------------------------------------------------------------

export interface AuthorClassInput {
  from_email: string | null
  from_name: string | null
  subject: string | null
  /** Body, truncated upstream to keep token usage tight. */
  body: string
  /** Optional extracted_identity blob (universal body parse output). When
   *  present, the judge can lean on parser hints like
   *  vendor_role / calendar_provider / form_lead. */
  extracted_identity?: Record<string, unknown> | null
}

// ---------------------------------------------------------------------------
// System prompt
// ---------------------------------------------------------------------------

export function buildAuthorClassSystemPrompt(): string {
  return `You are Bloom's author-class forensic classifier.

Bloom is a forensic identity-reconstruction system for wedding venues.
Every inbound interaction needs an author_class so downstream metrics
(knowledge-gap detection, classifier health, heat scoring, draft
training) can separate REAL human couple/operator signals from
automated platform noise. Without this, a Calendly "Sarah Smith booked
a tour" notification looks identical to a real couple message.

Your job: read the from-line + subject + body and commit to exactly
one author_class.

## AUTHOR CLASSES (pick exactly one)

1. **couple** — Written by the lead/couple themselves. Evidence:
   - Personal voice (first person, asks questions about pricing,
     dates, logistics, plans a visit)
   - From a personal email domain (gmail / outlook / yahoo / icloud /
     personal-name@personal-domain) OR a Knot/WW masked-relay address
     that wraps an actual couple message
   - The body reads like a person typing about THEIR wedding

2. **operator** — Written by venue staff (coordinator, Isadora,
   internal team). Evidence:
   - From an internal venue domain
   - Body discusses operations, coordinator-internal handoffs, or is
     authored in venue-staff voice ("we discussed", "I'll handle")
   - Rare on inbound — almost always outbound, but a venue-internal
     forward into the inbox can land here

3. **sage** — Generated by the AI agent (Sage / venue-specific AI
   name). Evidence:
   - Body signature matches the venue's AI name
   - Phrasing has the AI's hedge cadence ("I'll need to confirm",
     "Let me check with the coordinator")
   - Almost always outbound; on inbound this only happens when a
     multi-Gmail venue forwards Sage's reply back into the inbox

4. **platform_system** — Automated email from a SaaS tool. The body
   was authored by Calendly / Knot / WeddingWire / HoneyBook /
   Mailchimp / etc., not by a human. Evidence:
   - From-address contains "noreply", "no-reply", "donotreply",
     "notifications@", "system@", "info@platform"
   - Body matches a known platform shape:
       * "X booked a Y with you" (Calendly)
       * "New inquiry from X via The Knot" (Knot relay header)
       * "X scheduled a tour" (HoneyBook)
       * Out-of-office auto-replies
       * Mailchimp / Campaign Monitor / Constant Contact campaign
   - The body's structure is template-driven, not conversational
   - Knot/WW broadcast intake emails ARE platform_system at the
     envelope level even when they wrap a couple's quoted body; pick
     platform_system if the OUTERMOST authorship is the platform.
     The downstream universal extractor pulls the wrapped couple body
     into extracted_identity for forensic use; author_class describes
     who wrote what landed in the inbox.

5. **vendor** — Written by a wedding vendor (photographer, florist,
   planner, DJ, caterer). Evidence:
   - Body discusses vendor services / availability / portfolio
   - From a business domain matching a vendor pattern
   - Subject lines like "Photography inquiry", "Floral proposal",
     "Wedding planner introduction"

6. **unknown** — Use ONLY when the evidence is genuinely insufficient.
   Empty body + ambiguous from-address + no subject. Prefer 'unknown'
   over a wrong commitment; downstream consumers correctly skip
   unknown rows.

## CORE RULES

1. **Envelope wins.** If the email is a Calendly notification wrapping
   a couple's free-text answer, the AUTHOR is Calendly, not the
   couple. Pick platform_system. extracted_identity will surface the
   couple's wrapped text separately.

2. **From-domain is strong evidence.** noreply@/donotreply@/
   notifications@ + a transactional subject is high-confidence
   platform_system. Personal mail domains (gmail / outlook / yahoo /
   icloud) with conversational body is high-confidence couple.

3. **Body voice is decisive when from-domain is ambiguous.** A real
   couple from a small business domain still reads like a couple
   talking about their wedding. Lean on the body.

4. **Auto-reply / OOO are platform_system.** Even from a real couple's
   inbox, an "I'm currently out of the office" reply was generated by
   the email client, not the human.

5. **Reasoning must be short.** 1-2 sentences. Used for audit trail,
   not coordinator UI.

## OUTPUT SCHEMA

Return ONLY this JSON object — no prose preamble, no markdown fences:

{
  "author_class": "couple" | "operator" | "sage" | "platform_system" | "vendor" | "unknown",
  "reasoning": string (1-2 sentences)
}

Return ONLY the JSON. No markdown code fences. No prose before or after.`
}

// ---------------------------------------------------------------------------
// User prompt builder
// ---------------------------------------------------------------------------

export function buildAuthorClassUserPrompt(input: AuthorClassInput): string {
  const lines: string[] = []
  lines.push('# EMAIL TO CLASSIFY')
  lines.push('')
  lines.push(`from_email: ${input.from_email ?? '(none)'}`)
  lines.push(`from_name:  ${input.from_name ?? '(none)'}`)
  lines.push(`subject:    ${input.subject ?? '(none)'}`)
  lines.push('')

  if (input.extracted_identity && Object.keys(input.extracted_identity).length > 0) {
    lines.push('## UNIVERSAL EXTRACTOR HINTS (extracted_identity)')
    const ei = input.extracted_identity
    const hintKeys = [
      'calendar_provider',
      'form_lead',
      'platform',
      'vendor_role',
      'primary_email',
      'hear_source',
      'is_autoresponder',
    ]
    for (const k of hintKeys) {
      if (k in ei) {
        const v = ei[k]
        lines.push(`  ${k}: ${typeof v === 'string' ? v : JSON.stringify(v)}`)
      }
    }
    lines.push('')
  }

  lines.push('## BODY')
  const body = (input.body ?? '').trim()
  if (body.length === 0) {
    lines.push('(empty body)')
  } else {
    lines.push(body.slice(0, 2500))
  }
  lines.push('')

  lines.push('---')
  lines.push(
    'Classify the author_class of the email above. Return ONLY the JSON object.',
  )
  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// Validator — defensive parsing.
// ---------------------------------------------------------------------------

export interface ValidationFailure {
  ok: false
  error: string
}

export interface ValidationSuccess {
  ok: true
  output: AuthorClassOutput
}

export type ValidationResult = ValidationSuccess | ValidationFailure

function isString(v: unknown): v is string {
  return typeof v === 'string'
}

function isObject(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v)
}

const VALID_AUTHOR_CLASSES: readonly AuthorClass[] = [
  'couple',
  'operator',
  'sage',
  'platform_system',
  'vendor',
  'unknown',
]

export function validateAuthorClassOutput(raw: unknown): ValidationResult {
  if (!isObject(raw)) {
    return { ok: false, error: 'response is not a JSON object' }
  }

  const acRaw = raw.author_class
  if (
    !isString(acRaw) ||
    !(VALID_AUTHOR_CLASSES as readonly string[]).includes(acRaw)
  ) {
    return {
      ok: false,
      error: `author_class must be one of: ${VALID_AUTHOR_CLASSES.join(
        ', ',
      )} (got ${JSON.stringify(acRaw)})`,
    }
  }

  const reasoning = isString(raw.reasoning) ? raw.reasoning.trim() : ''

  return {
    ok: true,
    output: { author_class: acRaw as AuthorClass, reasoning },
  }
}
