/**
 * Bloom House — Wave 25 Wedding MBA presentation export.
 *
 * Anchor docs:
 *   - feedback_deep_fix_vs_bandaid.md (every export embeds the full
 *     calibration band — sample sizes, prompt versions, freshness — so
 *     external readers can reproduce the number months later)
 *   - PROMPT-BIAS-AUDIT.md (v1 asterisks on every cell)
 *
 * Generates a static HTML snapshot (browser-printable to PDF) of the
 * channel story arc + CAC reveal + quality + calibration footer. The
 * caller renders this server-side, or the front-end window.print()'s
 * the iframe. CSV / JSON variants are also available.
 *
 * The export FREEZES the snapshot into channel_presentation_exports so
 * the share-token URL is reproducible.
 */

import type { SupabaseClient } from '@supabase/supabase-js'
import { createServiceClient } from '@/lib/supabase/service'
import type { ChannelSnapshot, NarrationResult } from './types'
import { randomBytes } from 'crypto'

export type ExportFormat = 'pdf' | 'pptx' | 'csv' | 'json'

export interface ExportArgs {
  venueId: string
  venueLabel: string
  snapshot: ChannelSnapshot
  narrator: NarrationResult | null
  format: ExportFormat
  exportedBy?: string | null
  supabase?: SupabaseClient
}

export interface ExportResult {
  share_token: string
  download_url: string
  content_type: string
  /** Raw body for download endpoints to stream. */
  body: string
}

function generateShareToken(): string {
  // 32 URL-safe chars
  return randomBytes(24).toString('base64url')
}

function fmt$(cents: number | null): string {
  if (cents === null) return 'n/a'
  return `$${(cents / 100).toFixed(0)}`
}

function fmtPct(r: number | null): string {
  if (r === null) return 'n/a'
  return `${(r * 100).toFixed(1)}%`
}

function watermarkFooter(snapshot: ChannelSnapshot, venueLabel: string): string {
  const v1Pct =
    snapshot.sample_sizes.ae_total > 0
      ? (snapshot.confidence_signals.v1_contaminated_count /
          snapshot.sample_sizes.ae_total) *
        100
      : 0
  const promptVersions =
    snapshot.confidence_signals.prompt_versions_used.length === 0
      ? '(forensic-rule-only, no LLM judge)'
      : snapshot.confidence_signals.prompt_versions_used.join(', ')
  return `Generated by Bloom · bloomhq.ai · ${venueLabel} · ${snapshot.computed_at_iso} · v1-contam ${v1Pct.toFixed(1)}% · prompts: ${promptVersions}`
}

// ---------------------------------------------------------------------------
// HTML (browser-print to PDF)
// ---------------------------------------------------------------------------

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

function buildHtmlExport(snapshot: ChannelSnapshot, narrator: NarrationResult | null, venueLabel: string): string {
  const sa = snapshot.story_arc
  const segmentLabel: Record<string, string> = {
    discovery: 'Discovery',
    inquiry: 'Inquiry',
    validation: 'Validation',
    broadcast: 'Broadcast',
    cross_platform_footprint: 'Cross-platform footprint',
  }
  const segmentDescription: Record<string, string> = {
    discovery: 'Couples who actively chose this venue via this channel',
    inquiry: 'All inquiries that landed via this channel',
    validation: 'Couples found you elsewhere; this channel was the form',
    broadcast: 'Platform auto-distributed couples (did not actively pick you)',
    cross_platform_footprint: 'Channel in identity match, NOT a direct inquiry (excluded from CAC)',
  }
  const storyArcRows = sa
    .map(
      (c) => `
      <tr>
        <td><strong>${escapeHtml(segmentLabel[c.segment] ?? c.segment)}</strong>
            <div class="muted">${escapeHtml(segmentDescription[c.segment] ?? '')}</div></td>
        <td>${c.unique_weddings}</td>
        <td>${c.booked_weddings}</td>
        <td>${fmtPct(c.conversion_to_tour_rate_0_1)}</td>
        <td>${fmtPct(c.conversion_to_booked_rate_0_1)}</td>
        <td>${fmt$(c.avg_booking_value_cents)}</td>
        <td>${c.v1_contaminated_pct > 0 ? `*${c.v1_contaminated_pct.toFixed(1)}%` : '—'}</td>
      </tr>
    `,
    )
    .join('')

  const cacApparent = fmt$(snapshot.cost_metrics.cac_cents)
  const cacReal = fmt$(snapshot.cost_metrics.cac_excluding_broadcast_cents)
  const cacStrict = fmt$(snapshot.cost_metrics.cac_excluding_broadcast_and_crossplatform_cents)
  const spend = fmt$(snapshot.cost_metrics.spend_cents)

  const narrText = narrator?.refusal_reason
    ? `<p class="refusal">Narrator refused: ${escapeHtml(narrator.refusal_reason)}</p>`
    : narrator?.story_arc_paragraph
      ? `<p>${escapeHtml(narrator.story_arc_paragraph)}</p><p>${escapeHtml(narrator.cac_reveal_paragraph)}</p>${narrator.recommendation_if_any ? `<p class="rec">Recommendation: ${escapeHtml(narrator.recommendation_if_any)}</p>` : ''}`
      : '<p class="muted">Narrator not run.</p>'

  return `<!doctype html>
<html><head>
<meta charset="utf-8" />
<title>${escapeHtml(snapshot.display_name)} — ${escapeHtml(venueLabel)}</title>
<style>
  @page { size: letter; margin: 0.6in; }
  body { font-family: 'Helvetica Neue', Arial, sans-serif; color: #1c1917; max-width: 7.4in; margin: 0 auto; }
  h1 { font-family: Georgia, serif; font-size: 32px; margin: 0 0 4px 0; color: #2e4d3a; }
  h2 { font-family: Georgia, serif; font-size: 22px; margin: 28px 0 6px 0; color: #3f5d4b; border-bottom: 1px solid #d6d3d1; padding-bottom: 4px; }
  .subtitle { color: #57534e; margin: 0 0 18px 0; }
  table { width: 100%; border-collapse: collapse; margin: 8px 0 14px 0; font-size: 12px; }
  th, td { text-align: left; padding: 8px 10px; vertical-align: top; }
  th { background: #f5f5f4; font-size: 11px; text-transform: uppercase; letter-spacing: 0.04em; color: #57534e; }
  tr { border-bottom: 1px solid #e7e5e4; }
  .muted { color: #78716c; font-size: 10px; margin-top: 2px; }
  .reveal { background: #fef3c7; padding: 14px 16px; border-left: 4px solid #b45309; margin: 12px 0; }
  .reveal h3 { margin: 0 0 8px 0; font-family: Georgia, serif; font-size: 17px; color: #78350f; }
  .reveal .row { display: flex; justify-content: space-between; padding: 4px 0; }
  .reveal .label { color: #57534e; }
  .reveal .value { font-weight: 600; }
  .reveal .delta { color: #b45309; font-weight: 700; }
  .calibration { background: #f5f5f4; padding: 10px 12px; font-size: 11px; color: #57534e; margin-top: 16px; border-radius: 4px; }
  .calibration strong { color: #2e4d3a; }
  .refusal { background: #fee2e2; padding: 12px; border-left: 4px solid #b91c1c; font-size: 13px; }
  .rec { background: #ecfccb; padding: 10px 12px; border-left: 4px solid #4d7c0f; font-size: 13px; margin-top: 8px; }
  .footer { margin-top: 28px; font-size: 9px; color: #a8a29e; text-align: center; border-top: 1px solid #e7e5e4; padding-top: 8px; }
  .pull-quote { font-family: Georgia, serif; font-size: 18px; font-style: italic; color: #2e4d3a; padding: 14px 0; border-top: 2px solid #2e4d3a; border-bottom: 2px solid #2e4d3a; margin: 16px 0; }
</style>
</head>
<body>

<h1>${escapeHtml(snapshot.display_name)}</h1>
<p class="subtitle">${escapeHtml(venueLabel)} · ${snapshot.window_days}-day window · ${snapshot.sample_sizes.unique_weddings} unique weddings · ${snapshot.sample_sizes.ae_total} attribution events</p>

${narrator?.headline_pull_quote ? `<div class="pull-quote">"${escapeHtml(narrator.headline_pull_quote)}"</div>` : ''}

<h2>The story arc</h2>
<table>
  <thead>
    <tr>
      <th>Segment</th>
      <th>Unique weddings</th>
      <th>Booked</th>
      <th>Tour rate</th>
      <th>Book rate</th>
      <th>Avg value</th>
      <th>v1*</th>
    </tr>
  </thead>
  <tbody>
    ${storyArcRows}
  </tbody>
</table>

<h2>Narrative</h2>
${narrText}

<h2>Forensic CAC reveal</h2>
<div class="reveal">
  <h3>What the channel cost vs what it actually delivered</h3>
  <div class="row"><span class="label">Spend in window:</span> <span class="value">${spend}</span></div>
  <div class="row"><span class="label">Apparent CAC (all booked attributed):</span> <span class="value">${cacApparent}</span></div>
  <div class="row"><span class="label">Real CAC (excluding broadcast):</span> <span class="value">${cacReal}</span></div>
  <div class="row"><span class="label">Strict CAC (excluding broadcast + cross-platform-footprint):</span> <span class="value delta">${cacStrict}</span></div>
</div>

<h2>Quality signals</h2>
<table>
  <tbody>
    <tr><td><strong>Avg booking value</strong></td><td>${fmt$(snapshot.quality_metrics.avg_booking_value_cents)}</td></tr>
    <tr><td><strong>Median lead time (inquiry → event)</strong></td><td>${snapshot.quality_metrics.median_lead_time_days ?? 'n/a'} days</td></tr>
    <tr><td><strong>Avg review rating</strong></td><td>${snapshot.quality_metrics.avg_review_rating ?? 'n/a'} (n=${snapshot.quality_metrics.review_count})</td></tr>
    <tr><td><strong>Conversion funnel</strong></td><td>${snapshot.funnel.inquiries} inquiries → ${snapshot.funnel.tours} tours → ${snapshot.funnel.booked} booked · book rate ${fmtPct(snapshot.funnel.inquiry_to_booked_rate_0_1)}</td></tr>
  </tbody>
</table>

<div class="calibration">
  <strong>Calibration:</strong>
  ${snapshot.sample_sizes.ae_total} AE rows · v1-contamination ${
    snapshot.sample_sizes.ae_total > 0
      ? ((snapshot.confidence_signals.v1_contaminated_count / snapshot.sample_sizes.ae_total) * 100).toFixed(1)
      : '0.0'
  }% · v2-classified ${snapshot.confidence_signals.v2_classified_count} · forensic-rule-only ${snapshot.confidence_signals.null_classified_count} · data freshness ${snapshot.confidence_signals.data_freshness_iso} · prompt versions: ${
    snapshot.confidence_signals.prompt_versions_used.length === 0
      ? 'none (forensic only)'
      : snapshot.confidence_signals.prompt_versions_used.join(', ')
  } · computed via ${snapshot.confidence_signals.computed_with_function}
</div>

<div class="footer">
  ${escapeHtml(watermarkFooter(snapshot, venueLabel))}
</div>

</body></html>`
}

// ---------------------------------------------------------------------------
// CSV
// ---------------------------------------------------------------------------

function buildCsvExport(snapshot: ChannelSnapshot, venueLabel: string): string {
  const lines: string[] = []
  lines.push(`venue,channel,window_days,computed_at`)
  lines.push(`"${venueLabel}","${snapshot.display_name}",${snapshot.window_days},${snapshot.computed_at_iso}`)
  lines.push('')
  lines.push('segment,unique_weddings,booked_weddings,tour_weddings,conversion_to_tour_rate,conversion_to_booked_rate,avg_booking_value_cents,v1_contaminated_pct')
  for (const c of snapshot.story_arc) {
    lines.push(
      `${c.segment},${c.unique_weddings},${c.booked_weddings},${c.tour_weddings},${c.conversion_to_tour_rate_0_1 ?? ''},${c.conversion_to_booked_rate_0_1 ?? ''},${c.avg_booking_value_cents ?? ''},${c.v1_contaminated_pct.toFixed(2)}`,
    )
  }
  lines.push('')
  lines.push('metric,value')
  lines.push(`spend_cents,${snapshot.cost_metrics.spend_cents}`)
  lines.push(`apparent_cac_cents,${snapshot.cost_metrics.cac_cents ?? ''}`)
  lines.push(`real_cac_excluding_broadcast_cents,${snapshot.cost_metrics.cac_excluding_broadcast_cents ?? ''}`)
  lines.push(`strict_cac_excluding_broadcast_and_crossplatform_cents,${snapshot.cost_metrics.cac_excluding_broadcast_and_crossplatform_cents ?? ''}`)
  lines.push(`inquiry_to_booked_rate,${snapshot.funnel.inquiry_to_booked_rate_0_1 ?? ''}`)
  lines.push(`avg_review_rating,${snapshot.quality_metrics.avg_review_rating ?? ''}`)
  lines.push(`review_count,${snapshot.quality_metrics.review_count}`)
  lines.push(`median_lead_time_days,${snapshot.quality_metrics.median_lead_time_days ?? ''}`)
  lines.push('')
  lines.push(`# ${watermarkFooter(snapshot, venueLabel)}`)
  return lines.join('\n')
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Build the export body in the requested format and persist a frozen
 * snapshot row into channel_presentation_exports. Returns the share
 * token + download URL.
 */
export async function generateExport(args: ExportArgs): Promise<ExportResult> {
  const sb = args.supabase ?? createServiceClient()
  const shareToken = generateShareToken()
  const exportedAt = new Date().toISOString()

  let body: string
  let contentType: string
  if (args.format === 'csv') {
    body = buildCsvExport(args.snapshot, args.venueLabel)
    contentType = 'text/csv; charset=utf-8'
  } else if (args.format === 'json') {
    body = JSON.stringify(
      {
        venue_label: args.venueLabel,
        snapshot: args.snapshot,
        narrator: args.narrator,
        exported_at: exportedAt,
        watermark: watermarkFooter(args.snapshot, args.venueLabel),
      },
      null,
      2,
    )
    contentType = 'application/json; charset=utf-8'
  } else {
    // 'pdf' and 'pptx' both deliver HTML — the front-end print-to-pdf's
    // the HTML or the operator runs the page through Print → PDF. A
    // future Wave will swap in a real PDF library; the share-token
    // contract stays the same.
    body = buildHtmlExport(args.snapshot, args.narrator, args.venueLabel)
    contentType = 'text/html; charset=utf-8'
  }

  // Persist the frozen snapshot.
  const snapshotJsonb = {
    channel_slug: args.snapshot.channel_slug,
    source_platform: args.snapshot.source_platform,
    venue_label: args.venueLabel,
    window_days: args.snapshot.window_days,
    computed_at_iso: args.snapshot.computed_at_iso,
    story_arc: args.snapshot.story_arc,
    cost_reveal: args.snapshot.cost_metrics,
    funnel: args.snapshot.funnel,
    quality: args.snapshot.quality_metrics,
    sample_sizes: args.snapshot.sample_sizes,
    confidence_signals: args.snapshot.confidence_signals,
    narrator_output: args.narrator,
  }

  const { error } = await sb.from('channel_presentation_exports').insert({
    venue_id: args.venueId,
    exported_at: exportedAt,
    exported_by: args.exportedBy ?? null,
    channel_slug: args.snapshot.channel_slug,
    format: args.format,
    share_token: shareToken,
    snapshot_jsonb: snapshotJsonb,
  })
  if (error) {
    // Soft-fail: still return the body. The operator gets the export,
    // the audit row is missing (lower priority).
    // eslint-disable-next-line no-console
    console.warn('[channel-intel-hub.export] persist failed:', error.message)
  }

  return {
    share_token: shareToken,
    download_url: `/api/public/channels/exports/${shareToken}`,
    content_type: contentType,
    body,
  }
}

/**
 * Render a frozen snapshot (stored in channel_presentation_exports) as
 * HTML so the public-share endpoint can serve it without re-deriving.
 */
export function renderFrozenExport(
  snapshotJsonb: {
    venue_label?: string
    channel_slug?: string
    source_platform?: string
    window_days?: number
    computed_at_iso?: string
    story_arc?: unknown
    cost_reveal?: unknown
    funnel?: unknown
    quality?: unknown
    sample_sizes?: unknown
    confidence_signals?: unknown
    narrator_output?: unknown
  },
): string {
  // Lightweight render: reconstruct the ChannelSnapshot shape enough for
  // the HTML renderer. The frozen jsonb is exhaustive enough that we
  // don't need to re-derive anything.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const s = snapshotJsonb as any
  const fake: ChannelSnapshot = {
    venue_id: '',
    channel_slug: s.channel_slug ?? 'unknown',
    source_platform: s.source_platform ?? 'unknown',
    display_name: s.channel_slug ?? 'unknown',
    computed_at_iso: s.computed_at_iso ?? new Date().toISOString(),
    window_days: s.window_days ?? 90,
    role_breakdown: { acquisition: 0, validation: 0, conversion: 0, mixed: 0, unknown: 0 },
    intent_breakdown: { targeted: 0, broadcast: 0, validation: 0, unknown: 0 },
    funnel: s.funnel ?? {
      inquiries: 0,
      tours: 0,
      booked: 0,
      inquiry_to_tour_rate_0_1: null,
      tour_to_booked_rate_0_1: null,
      inquiry_to_booked_rate_0_1: null,
      drop_inquiry_to_tour_0_1: null,
      drop_tour_to_booked_0_1: null,
    },
    cost_metrics: s.cost_reveal ?? {
      spend_cents: 0,
      cac_cents: null,
      cac_excluding_broadcast_cents: null,
      cac_excluding_broadcast_and_crossplatform_cents: null,
      cost_per_inquiry_cents: null,
      cost_per_tour_cents: null,
    },
    quality_metrics: s.quality ?? {
      avg_booking_value_cents: null,
      median_lead_time_days: null,
      avg_review_rating: null,
      review_count: 0,
      persona_distribution: {},
    },
    sample_sizes: s.sample_sizes ?? {
      unique_weddings: 0,
      ae_total: 0,
      weddings_per_role: { acquisition: 0, validation: 0, conversion: 0, mixed: 0, unknown: 0 },
      weddings_per_intent: { targeted: 0, broadcast: 0, validation: 0, unknown: 0 },
      weddings_per_story_arc: {
        discovery: 0,
        inquiry: 0,
        validation: 0,
        broadcast: 0,
        cross_platform_footprint: 0,
      },
    },
    confidence_signals: s.confidence_signals ?? {
      v1_contaminated_count: 0,
      v2_classified_count: 0,
      null_classified_count: 0,
      data_freshness_iso: new Date().toISOString(),
      prompt_versions_used: [],
      window_days: s.window_days ?? 90,
      computed_with_function: 'computeChannelSnapshot',
    },
    story_arc: s.story_arc ?? [],
    disagreement_findings_count: 0,
  }
  return buildHtmlExport(fake, s.narrator_output ?? null, s.venue_label ?? 'Venue')
}
