#!/usr/bin/env node
/**
 * Generate SITEMAP.md from src/app source structure.
 *
 * Walks src/app for all page.tsx and route.ts files, groups by top-level
 * segment, counts them, and regenerates SITEMAP.md with current counts
 * and a generated-at timestamp.
 *
 * Usage: node scripts/gen-sitemap.mjs
 */

import { promises as fs } from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.join(__dirname, '..')
const APP_DIR = path.join(ROOT, 'src', 'app')
const SITEMAP_PATH = path.join(ROOT, 'SITEMAP.md')

/**
 * Walk a directory recursively and collect page.tsx + route.ts files.
 */
async function walkApp(dir) {
  const entries = await fs.readdir(dir, { withFileTypes: true })
  const files = { pages: [], routes: [] }

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name)

    // Skip special directories
    if (entry.name.startsWith('.') || entry.name.startsWith('node_modules')) continue

    if (entry.isDirectory()) {
      const subFiles = await walkApp(fullPath)
      files.pages.push(...subFiles.pages)
      files.routes.push(...subFiles.routes)
    } else if (entry.name === 'page.tsx') {
      files.pages.push(fullPath)
    } else if (entry.name === 'route.ts') {
      files.routes.push(fullPath)
    }
  }

  return files
}

/**
 * Extract top-level segment from a full path.
 * e.g. src/app/(platform)/agent/inbox/page.tsx → 'agent'
 */
function getTopLevelSegment(fullPath) {
  const relPath = path.relative(APP_DIR, fullPath)
  const parts = relPath.split(path.sep)

  // Skip route groups (parentheses)
  for (const part of parts) {
    if (!part.startsWith('(') && !part.endsWith('.tsx') && part !== '') {
      return part
    }
  }

  return 'root'
}

/**
 * Main: count and report.
 */
async function main() {
  const files = await walkApp(APP_DIR)
  const counts = {
    pages: files.pages.length,
    routes: files.routes.length,
    bySegment: new Map(),
  }

  // Group by top-level segment
  for (const file of files.pages) {
    const seg = getTopLevelSegment(file)
    if (!counts.bySegment.has(seg)) {
      counts.bySegment.set(seg, { pages: 0, routes: 0 })
    }
    counts.bySegment.get(seg).pages++
  }

  for (const file of files.routes) {
    const seg = getTopLevelSegment(file)
    if (!counts.bySegment.has(seg)) {
      counts.bySegment.set(seg, { pages: 0, routes: 0 })
    }
    counts.bySegment.get(seg).routes++
  }

  // Log summary
  console.log(`\nSitemap Summary (${new Date().toISOString().split('T')[0]}):`)
  console.log(`Total page.tsx:  ${counts.pages}`)
  console.log(`Total route.ts:  ${counts.routes}`)
  console.log(`\nBy segment:`)

  for (const [seg, c] of [...counts.bySegment.entries()].sort()) {
    if (c.pages > 0 || c.routes > 0) {
      console.log(`  ${seg}: ${c.pages} pages, ${c.routes} routes`)
    }
  }

  // Generate markdown
  const timestamp = new Date().toISOString().split('T')[0]
  let markdown = `# The Bloom House — Complete Sitemap

**Stack:** Next.js 16 (App Router) + TypeScript + Supabase
**Total:** ${counts.pages} pages, ${counts.routes} API routes
**Generated:** ${timestamp}

---

## Platform pages (${counts.bySegment.get('agent')?.pages ?? 0 + counts.bySegment.get('intel')?.pages ?? 0 + counts.bySegment.get('portal')?.pages ?? 0 + counts.bySegment.get('settings')?.pages ?? 0 + counts.bySegment.get('admin')?.pages ?? 0 + counts.bySegment.get('onboarding')?.pages ?? 0 + counts.bySegment.get('setup')?.pages ?? 0})

Agent, Intel, Portal, Settings, Admin, Onboarding, Setup.

| Segment | Pages | Routes |
|---------|-------|--------|
`

  for (const [seg, c] of [...counts.bySegment.entries()].sort()) {
    if (seg !== 'root' && seg !== 'couple' && seg !== 'demo') {
      markdown += `| ${seg} | ${c.pages} | ${c.routes} |\n`
    }
  }

  markdown += `

## Couple portal (\`/couple/[slug]/...\`)
| Segment | Pages | Routes |
|---------|-------|--------|
| couple | ${counts.bySegment.get('couple')?.pages ?? 0} | ${counts.bySegment.get('couple')?.routes ?? 0} |

## Public & Auth
| Segment | Pages | Routes |
|---------|-------|--------|
| root | ${counts.bySegment.get('root')?.pages ?? 0} | ${counts.bySegment.get('root')?.routes ?? 0} |
| demo | ${counts.bySegment.get('demo')?.pages ?? 0} | ${counts.bySegment.get('demo')?.routes ?? 0} |

---

Note: This sitemap is auto-generated by \`scripts/gen-sitemap.mjs\`. Run it to update counts when pages or routes change.
`

  // Write file
  await fs.writeFile(SITEMAP_PATH, markdown, 'utf8')
  console.log(`\n✅ Wrote ${SITEMAP_PATH}`)
}

main().catch(err => {
  console.error('Error:', err)
  process.exit(1)
})
