import { NextRequest, NextResponse } from 'next/server'
import { getPlatformAuth, unauthorized, badRequest, serverError } from '@/lib/api/auth-helpers'
import { createServiceClient } from '@/lib/supabase/service'
import { generateReviewResponse } from '@/lib/services/brain/review-response'

export const maxDuration = 60

/**
 * POST /api/intel/reviews/[id]/draft-response
 *
 * Asks the venue's AI assistant to draft a public response to a
 * review. Used on /intel/reviews — coordinator hits the Sage draft
 * button on the row, edits the result in the textarea, then saves.
 *
 * The draft is generated by `generateReviewResponse`, which reuses
 * the SAME 4-layer personality prompt as the email-reply Sage so
 * the public voice matches the inbox voice. Banned/approved-phrase
 * rules from voice_preferences apply, plus a task-specific block
 * that forces the model to reference a specific moment from the
 * review and shifts tone for low-rating reviews.
 */
export async function POST(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  const auth = await getPlatformAuth()
  if (!auth) return unauthorized()
  if (auth.isDemo) {
    return NextResponse.json(
      { error: 'Response drafting is not available in demo mode' },
      { status: 403 },
    )
  }

  const { id } = await params
  if (!id) return badRequest('review id is required')

  const supabase = createServiceClient()
  const { data: review, error: fetchErr } = await supabase
    .from('reviews')
    .select('id, venue_id, reviewer_name, rating, title, body, source, response_text')
    .eq('id', id)
    .single()

  if (fetchErr || !review) return badRequest('review not found')
  if (review.venue_id !== auth.venueId) {
    return NextResponse.json({ error: 'forbidden' }, { status: 403 })
  }

  try {
    const result = await generateReviewResponse(review.venue_id, {
      id: review.id as string,
      reviewer_name: (review.reviewer_name as string | null) ?? null,
      rating: (review.rating as number | null) ?? null,
      title: (review.title as string | null) ?? null,
      body: review.body as string,
      source: (review.source as string | null) ?? null,
      response_text: (review.response_text as string | null) ?? null,
    })

    if (!result.draft) {
      return NextResponse.json({ error: 'empty draft' }, { status: 502 })
    }

    return NextResponse.json({
      ok: true,
      draft: result.draft,
      prompt_version: result.promptVersion,
    })
  } catch (err) {
    return serverError(err)
  }
}
