/**
 * Bloom House: Date-windows helper (T5-Rixey-LL).
 *
 * Single source of truth for "what's the REAL event-date column for this
 * table?" — distinct from `created_at` (which is when the row landed in
 * Supabase).
 *
 * The post-import looks-broken class of bugs all share the same root
 * cause: when a venue imports 12 months of historical HoneyBook +
 * Calendly + web-form data on Day 0 of onboarding, every row gets
 * `created_at = now()`. Coordinator-facing stats that window by
 * `created_at` then say "0 inquiries this week" even though 200
 * historical inquiries just landed (their REAL inquiry_date stretches
 * back a year).
 *
 * Fix: every coordinator-facing time-based stat windows on the REAL
 * event-date column, not the import date. This module encodes the
 * mapping so future code can ASK for the canonical column rather than
 * hardcode `created_at`.
 *
 * Bias toward correctness — when in doubt, use the real event date.
 *
 * Telemetry exception: tables where created_at IS the meaningful
 * timestamp (api_costs.created_at = when the API call was made;
 * cron_runs.started_at = when the cron tick ran) are listed in
 * TELEMETRY_TABLES below, and the CI guard check-no-coordinator-facing-
 * created-at allowlists them.
 */

import type { SupabaseClient } from '@supabase/supabase-js'

// ---------------------------------------------------------------------------
// Doctrine: real event-date column per table
// ---------------------------------------------------------------------------

/**
 * Tables whose REAL event-date column is something other than created_at.
 *
 * For each table, the listed column is the one coordinator-facing
 * stats MUST use to window by the underlying event time (not the
 * import time).
 *
 * weddings has THREE event dates depending on intent:
 *   - inquiry_date: "when did this lead arrive"  (use for new-inquiries
 *                   counts, response-time, source-mix-by-arrival)
 *   - booked_at:    "when did they sign"         (use for booking
 *                   velocity, weekly-revenue, source-mix-by-booking)
 *   - wedding_date: "when's the event"           (use for upcoming-
 *                   events lists + capacity windows)
 * Callers pick the intent. The table mapping below returns the most
 * common one (`inquiry_date`) as the default for "real event date" when
 * no intent is specified — bias toward "when did this signal arrive".
 */
export const REAL_DATE_COLUMN: Readonly<Record<string, string>> = Object.freeze({
  // Pipeline event tables — REAL event date wins.
  weddings: 'inquiry_date',          // when the lead first appeared
  interactions: 'timestamp',         // when the email was sent / received
                                      // (legacy column name; equivalent to
                                      //  occurred_at in the schema doctrine)
  tours: 'scheduled_at',             // when the tour happens / happened
  engagement_events: 'occurred_at',  // when the signal fired
  attribution_events: 'occurred_at', // when the touch happened
  tangential_signals: 'signal_date', // when the platform signal fired
  candidate_identities: 'first_seen', // when this identity first appeared

  // Voice signals
  phrase_usage: 'used_at',
  voice_preferences: 'signal_date',  // backfilled to underlying source.
                                      // Live entries default to created_at via DB default.
  voice_training_responses: 'signal_date',  // same shape as voice_preferences

  // Lifecycle stamps
  lost_deals: 'lost_at',
  lead_score_history: 'calculated_at',

  // Macro / cron-fed series
  cultural_moments: 'start_at',      // when the trend started
  marketing_spend: 'period_month',   // the month being attributed
  pricing_history: 'effective_date', // when the price change took effect

  // Tour-specific lifecycle
  draft_feedback: 'created_at',      // exception: action timestamp IS
                                      // when the coordinator acted.
                                      // Listed for clarity even though
                                      // it equals created_at.
})

/**
 * Telemetry tables — `created_at` (or a similar processing-time stamp)
 * IS the meaningful column. Listed for the CI guard.
 */
export const TELEMETRY_TABLES: ReadonlySet<string> = new Set([
  'api_costs',          // when the API call was billed
  'cron_runs',          // when the cron tick fired (uses started_at)
  'metered_events',     // when usage was observed
  'admin_notifications', // when Bloom queued the notification
  'pulse_snoozes',      // when the coordinator snoozed/dismissed
  'anomaly_alerts',     // when the alert was generated by the engine
  'intelligence_insights', // when the insight was generated by the engine
  'ai_briefings',       // when the briefing was generated
  'planning_notes',     // when the note was extracted (dedupe-only use of created_at)
  'drafts',             // when Sage drafted (workflow telemetry)
  'messages',           // couple-portal message timestamp
  'sage_conversations', // chat-message timestamp
  'checklist_items',    // workflow timestamp
  'audit_logs',         // by definition
  'essentials_action_log', // when the user took the action
  'paused_period_skipped', // when the cron skipped
  'api_health_pings',   // probe timestamp
  'voice_training_sessions', // started_at IS the event timestamp
])

// ---------------------------------------------------------------------------
// Resolver
// ---------------------------------------------------------------------------

export type RealDateIntent = 'arrival' | 'booking' | 'event'

/**
 * Resolve the real event-date column for a table.
 *
 * Optional `intent` differentiates the multi-stamp cases (currently
 * only `weddings`):
 *   - 'arrival' → inquiry_date  (default; "when did the lead arrive")
 *   - 'booking' → booked_at     ("when did they sign")
 *   - 'event'   → wedding_date  ("when's the event")
 *
 * For every other table, the intent argument is ignored.
 *
 * Returns `null` when the table is in TELEMETRY_TABLES — callers should
 * keep using `created_at` (or the table-specific telemetry stamp).
 */
export function realDateColumn(
  table: string,
  intent: RealDateIntent = 'arrival',
): string | null {
  if (TELEMETRY_TABLES.has(table)) return null

  if (table === 'weddings') {
    if (intent === 'booking') return 'booked_at'
    if (intent === 'event') return 'wedding_date'
    return 'inquiry_date'
  }

  return REAL_DATE_COLUMN[table] ?? null
}

// ---------------------------------------------------------------------------
// Convenience query wrapper
// ---------------------------------------------------------------------------

export interface DateWindow {
  /** ISO timestamp lower bound (inclusive). */
  gteIso: string
  /** Optional ISO timestamp upper bound (exclusive when used with .lt,
   *  inclusive when used with .lte — caller's choice via `inclusiveEnd`). */
  lteIso?: string
  /** When true (default), end bound applies as `.lte`. When false, as `.lt`. */
  inclusiveEnd?: boolean
}

/**
 * Apply a date window to a Supabase query using the REAL event-date
 * column for the given table. Saves callers from hardcoding column
 * names in every coordinator-facing stat.
 *
 * Example:
 *   const q = supabase.from('weddings').select('id', { count: 'exact', head: true })
 *     .eq('venue_id', venueId)
 *   const counted = await applyWindow(q, 'weddings', { gteIso: sinceIso })
 *
 * For TELEMETRY_TABLES this falls back to `created_at` (or `started_at`
 * for cron_runs) so the helper still works on those — the CI guard
 * separately catches accidental coordinator-facing reads.
 */
export function applyWindow<
  Q extends {
    gte: (col: string, val: string) => Q
    lte: (col: string, val: string) => Q
    lt: (col: string, val: string) => Q
  },
>(
  query: Q,
  table: string,
  window: DateWindow,
  intent: RealDateIntent = 'arrival',
): Q {
  let column = realDateColumn(table, intent)
  if (!column) {
    // Telemetry table: fall back to the conventional column.
    column = table === 'cron_runs' ? 'started_at' : 'created_at'
  }
  let q = query.gte(column, window.gteIso)
  if (window.lteIso) {
    q = window.inclusiveEnd === false
      ? q.lt(column, window.lteIso)
      : q.lte(column, window.lteIso)
  }
  return q
}

/**
 * Tiny ergonomic wrapper for the common "weddings inquiries since X"
 * shape — saves the ceremony around the count-only query.
 *
 * Returns `null` on error so callers don't have to thread through
 * the Supabase error type.
 */
export async function countSince(
  supabase: SupabaseClient,
  table: string,
  venueId: string,
  sinceIso: string,
  intent: RealDateIntent = 'arrival',
): Promise<number | null> {
  const column = realDateColumn(table, intent) ?? 'created_at'
  const { count, error } = await supabase
    .from(table)
    .select('id', { count: 'exact', head: true })
    .eq('venue_id', venueId)
    .gte(column, sinceIso)
  if (error) return null
  return count ?? 0
}
