-- Migration 114: drafts.follow_up_step
--
-- Adds a nullable column on drafts that records which sequence step a
-- follow-up draft belongs to (e.g. 'follow_up_3_day', 'follow_up_7_day',
-- 'follow_up_final'). This unblocks the broken follow-up cron, which
-- previously tried to encode the step in `context_type` and silently
-- failed against the CHECK constraint that allows only 'inquiry' /
-- 'client'.
--
-- Per Playbook 10.3: follow-ups go through the same approval / auto-send
-- path as inbound replies; sliders apply. Therefore context_type for a
-- follow-up draft is 'inquiry' (so auto_send_rules lookups by context
-- still match), and the step is metadata.
--
-- The column is nullable: regular inquiry/client drafts have follow_up_step
-- = NULL. Counting follow-ups for a wedding is `WHERE follow_up_step IS
-- NOT NULL`, replacing the prior `LIKE 'follow_up_%'` on context_type
-- which could never have matched.

ALTER TABLE drafts ADD COLUMN IF NOT EXISTS follow_up_step text;

COMMENT ON COLUMN drafts.follow_up_step IS
  'Set when a draft was generated by the follow-up sequence cron. Values: '
  '''follow_up_3_day'', ''follow_up_7_day'', ''follow_up_final''. NULL for '
  'normal pipeline-generated drafts. Counted by follow-up-sequences.ts to '
  'determine which step to send next.';

-- Index to make the per-wedding follow-up count cheap.
CREATE INDEX IF NOT EXISTS idx_drafts_follow_up_step
  ON drafts (wedding_id, follow_up_step)
  WHERE follow_up_step IS NOT NULL;
