-- ---------------------------------------------------------------------------
-- 293_interactions_author_class.sql  (Wave 27)
-- ---------------------------------------------------------------------------
-- Adds the third dimension to interactions: WHO authored the signal.
--
-- The platform already has:
--   - direction (inbound / outbound) — which way the message flows
--   - type (email / call / voicemail / sms / meeting / web_form) — what shape
--   - signal_class (source / touchpoint / crm / outcome / unclassified) — its role
--
-- Missing: author_class — who actually composed the content. A Calendly
-- notification ("Sarah Smith booked a tour") is direction=inbound type=email
-- but the AUTHOR is Calendly's system, not Sarah. Today downstream consumers
-- (knowledge-gap detector, classifier health metric, heat scoring, draft
-- training) can't tell those apart from real couple messages — they
-- contaminate every metric they touch.
--
-- author_class values:
--   couple           — written by a couple/lead (the canonical case)
--   operator         — written by venue staff (Isadora, coordinator)
--   sage             — generated by the AI agent (Sage / venue-specific name)
--   platform_system  — automated email from Calendly, Knot relay, HoneyBook,
--                      autoresponder, OOO reply, mailchimp campaign, etc.
--   vendor           — written by a wedding vendor (photographer, florist)
--   unknown          — pipeline could not classify (DEFAULT)
--
-- Default 'unknown' is intentional. The Haiku classifier in
-- src/lib/services/email/author-classifier.ts runs at write time and
-- updates the row; existing rows are backfilled by the cron job.
-- ---------------------------------------------------------------------------

ALTER TABLE interactions
  ADD COLUMN IF NOT EXISTS author_class TEXT NOT NULL DEFAULT 'unknown';

ALTER TABLE interactions DROP CONSTRAINT IF EXISTS interactions_author_class_check;
ALTER TABLE interactions
  ADD CONSTRAINT interactions_author_class_check
  CHECK (author_class IN ('couple', 'operator', 'sage', 'platform_system', 'vendor', 'unknown'));

-- Tracks which prompt version classified the row, so when we bump the
-- author-class prompt we can re-classify only what's stale.
ALTER TABLE interactions
  ADD COLUMN IF NOT EXISTS author_class_prompt_version TEXT;

ALTER TABLE interactions
  ADD COLUMN IF NOT EXISTS author_class_decided_at TIMESTAMPTZ;

-- Outbound rows backfill as 'operator' synchronously. The Haiku classifier
-- (author-classifier.ts) later upgrades to 'sage' when it detects the AI-
-- disclosure footer in the body — which is the actual ground-truth signal
-- for "this was Sage-authored" anyway. drafts does not carry a direct FK
-- to the resulting outbound interaction, so we don't try to do that join
-- here. The Haiku pass handles the refinement.
UPDATE interactions
SET author_class = 'operator',
    author_class_prompt_version = 'rules-v1',
    author_class_decided_at = NOW()
WHERE direction = 'outbound'
  AND author_class = 'unknown';

-- Index used by the backfill cron + the classifier-health metric to find
-- inbound rows still pending classification.
CREATE INDEX IF NOT EXISTS idx_interactions_author_class_pending
  ON interactions (venue_id, author_class)
  WHERE author_class = 'unknown' AND direction = 'inbound';

COMMENT ON COLUMN interactions.author_class IS
  'Wave 27: who authored this signal. Defaults to unknown; Haiku classifier sets to couple/operator/sage/platform_system/vendor at write time. Backfill cron handles legacy rows.';

NOTIFY pgrst, 'reload schema';
