-- ---------------------------------------------------------------------------
-- 308_agency_storage_and_tbh_reports.sql  (Wave 6E depth pass)
-- ---------------------------------------------------------------------------
-- Two pieces in one migration because they're both small and ship as a
-- single feature: real file storage for agency_documents, and a
-- persisted history table for TBH Reports so the LLM bill stays
-- bounded (one generation per period, with re-run on demand).
--
-- Piece 1 — Supabase Storage bucket for native file uploads
--
--   migration 307's agency_documents has file_url (text) but the only
--   way to populate it was paste a Google Drive / Dropbox link. The
--   depth pass adds true native uploads via a private bucket. All
--   access goes through API routes — the bucket itself is locked to
--   service-role to keep RLS reasoning simple (the agency_documents
--   row is the canonical permission boundary; signed URLs derived
--   from it carry the access decision).
--
--   Path scheme: {agency_id}/{document_id}-{slugified-name}.{ext}
--   Size limit:  25 MB (storage.buckets.file_size_limit, bytes).
--   Allowed MIME types: enforced at the API layer (not bucket-level
--                       because Supabase bucket allowed_mime_types
--                       triggers schema-cache reload churn).
--
-- Piece 2 — tbh_reports persisted history
--
--   Each TBH Report (LLM-generated narrative + structured snapshot)
--   gets a row so:
--     - Operator can review what was sent vs what numbers shifted
--     - LLM bill is bounded (don't regenerate on every page view)
--     - Coordinator + agency can reference the report by short_code
--       in conversation
--
--   Schema: one row per (agency_id, period_start, period_end, mode).
--   Mode = 'internal' | 'shareable' (per bloom-tbh-brand-asset
--   doctrine — sharp framing for venue ops, softer for sending to
--   the agency).
--
-- Idempotent. No BEGIN/COMMIT wrapper (Wave 23 doctrine).
-- ---------------------------------------------------------------------------

-- ============================================================================
-- STEP 1 — Storage bucket: agency-documents
-- ============================================================================
-- Private bucket. Service-role does all writes; signed URLs handle reads.
-- file_size_limit is in BYTES (25 MB). public=false so no anonymous
-- inference of object paths.

INSERT INTO storage.buckets (id, name, public, file_size_limit)
VALUES ('agency-documents', 'agency-documents', false, 26214400)
ON CONFLICT (id) DO UPDATE
  SET public = EXCLUDED.public,
      file_size_limit = EXCLUDED.file_size_limit;

-- Lock all direct authenticated access to the bucket. Reads happen via
-- short-lived signed URLs generated by /api/intel/agencies/[id]/
-- documents/[documentId]/download after the API validates the user
-- can see the parent agency_documents row.

DROP POLICY IF EXISTS "agency_documents_storage_service_all"
  ON storage.objects;
CREATE POLICY "agency_documents_storage_service_all"
  ON storage.objects
  FOR ALL
  TO service_role
  USING (bucket_id = 'agency-documents')
  WITH CHECK (bucket_id = 'agency-documents');

-- ============================================================================
-- STEP 2 — tbh_reports (persisted report history)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.tbh_reports (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  agency_id uuid NOT NULL REFERENCES public.marketing_agencies(id) ON DELETE CASCADE,
  venue_id uuid REFERENCES public.venues(id) ON DELETE CASCADE,

  -- Identifier the operator can quote in conversation ("send me TBH-2026-Q2-04").
  -- 8-char base36 string, derived from id but stored separately so it's
  -- queryable + URL-safe.
  short_code text NOT NULL,

  -- Period this report covers. period_end is inclusive.
  period_start date NOT NULL,
  period_end date NOT NULL,

  -- Mode the report was generated in.
  --   internal:  sharp framing, surfaces conflicts directly.
  --   shareable: softer framing, designed to send to the agency.
  mode text NOT NULL DEFAULT 'internal'
    CHECK (mode IN ('internal', 'shareable')),

  -- LLM-generated narrative pieces.
  executive_summary text,
  conflict_findings text,
  recommendations text,
  notes_for_agency text, -- only populated for mode='shareable'

  -- Full structured snapshot of every number that backs the narrative.
  -- Stored so re-rendering the report doesn't need a fresh compute.
  -- Shape (see computeTbhReport in service):
  --   {
  --     roi: { totalSpendCents, firstTouchLeads, ... },
  --     breakdown: { perChannel: [...], monthlyTrend: [...], personaCounts },
  --     kpiPerformance: [...],
  --     coverage: { pixelInstalledAt, googleAdsOAuth, calendlyQa, ... },
  --     activityHighlights: [...],
  --     engagements: [...]
  --   }
  snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,

  -- LLM metadata for cost + reproducibility tracking.
  prompt_version text,
  llm_model text,
  llm_cost_cents integer NOT NULL DEFAULT 0,
  llm_input_tokens integer,
  llm_output_tokens integer,

  generated_by uuid REFERENCES public.user_profiles(id),
  generated_at timestamptz NOT NULL DEFAULT now(),

  -- Soft delete (lets a coordinator hide a report without losing the
  -- history vs new reports for the same period).
  deleted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT tbh_reports_short_code_format
    CHECK (length(short_code) BETWEEN 6 AND 16
           AND short_code ~ '^[A-Z0-9-]+$'),
  CONSTRAINT tbh_reports_period_valid
    CHECK (period_end >= period_start)
);

COMMENT ON TABLE public.tbh_reports IS
  'owner:intelligence. Wave 6E depth. Persisted history of TBH Reports '
  '(forensic agency-performance reports). One row per (agency, period, '
  'mode). LLM cost capped because regeneration is operator-triggered, '
  'not page-view-triggered. snapshot column holds the structured data '
  'used to render so the report is reproducible even if upstream '
  'metrics drift. short_code is the human handle for the report. '
  'Migration 308.';

COMMENT ON COLUMN public.tbh_reports.mode IS
  'internal: sharp framing for venue operators. shareable: softer copy '
  'suitable for forwarding to the agency. Per bloom-tbh-brand-asset.';

COMMENT ON COLUMN public.tbh_reports.snapshot IS
  'Full structured dump of every number behind the narrative. Lets the '
  'report render without re-computing + lets the operator inspect the '
  'exact inputs months later when metrics have drifted.';

CREATE UNIQUE INDEX IF NOT EXISTS uq_tbh_reports_short_code
  ON public.tbh_reports (short_code);

CREATE INDEX IF NOT EXISTS idx_tbh_reports_agency_period
  ON public.tbh_reports (agency_id, period_end DESC)
  WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_tbh_reports_venue
  ON public.tbh_reports (venue_id, generated_at DESC)
  WHERE venue_id IS NOT NULL AND deleted_at IS NULL;

-- ============================================================================
-- STEP 3 — RLS for tbh_reports (mirror agency-profile pattern)
-- ============================================================================

ALTER TABLE public.tbh_reports ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "tbh_reports_select" ON public.tbh_reports;
CREATE POLICY "tbh_reports_select" ON public.tbh_reports
  FOR SELECT TO authenticated
  USING (
    agency_id IN (SELECT id FROM public.marketing_agencies)
    OR public.is_super_admin()
  );

DROP POLICY IF EXISTS "tbh_reports_modify" ON public.tbh_reports;
CREATE POLICY "tbh_reports_modify" ON public.tbh_reports
  FOR ALL TO authenticated
  USING (
    agency_id IN (SELECT id FROM public.marketing_agencies)
    OR public.is_super_admin()
  )
  WITH CHECK (
    agency_id IN (SELECT id FROM public.marketing_agencies)
    OR public.is_super_admin()
  );

DROP POLICY IF EXISTS "tbh_reports_service" ON public.tbh_reports;
CREATE POLICY "tbh_reports_service" ON public.tbh_reports
  FOR ALL TO service_role
  USING (true) WITH CHECK (true);

NOTIFY pgrst, 'reload schema';
